### ISSUE TITLE
CFP : ajouter la ville du speaker dans le formulaire de soumission

### ISSUE THREAD

**Issue by CecileAmrl** [afup/web#1032]
À l'heure actuelle, quand un speaker propose un sujet à un CFP il remplit plusieurs informations dans un formulaire (nom, prénom, twitter, bio...). Serait-il possible d'ajouter dans ce formulaire un champ Ville afin que les orgas puissent mieux anticiper les éventuels coûts de déplacement ?

**Comment by stakovicz** [comment]
Visiblement c'est en prod !
https://github.com/afup/web/pull/1105#issuecomment-954476845
