### ISSUE TITLE
Erreur 500 sur "Recevoir invitation slack"

### ISSUE THREAD

**Issue by Kleinast** [afup/web#1050]
Bonjour,

Je n'arrive pas a rejoindre le slack afup par le biai du lien sur le site de l'afup:
J'ai une erreur 500 à cette url: https://afup.org/admin/member/slack-invite

**Comment by agallou** [comment]
Bonjour @Kleinast 

Vous avez déjà un compte sur le slack membres afup, c'est pour cela qu'il y a une erreur 500 en accédant à cette URL.

Si vous allez à cette adresse : https://afup.org/member/

![Screenshot_2021-02-02 Afup - Association française des utilisateurs de PHP](https://user-images.githubusercontent.com/320372/106598842-95d19580-6558-11eb-8fd5-79b44d172a69.png)

en étant connecté avec votre compte AFUP, vous devriez voir un bouton "Accéder" en dessous de "
Slack membres AFUP" qui vous enverra sur le slack membres.

Arrivez-vous donc bien à accéder au slack ?

Par curiosité, comment avez vous obtenu le lien https://afup.org/admin/member/slack-invite ? (celui-ci ne s'affiche qu'une seulement qu'une fois, ensuite c'est le lien http://afup-membres.slack.com/ qui est affiché).

**Comment by Kleinast** [comment]
![screenshot-afup org-2021 02 02](https://user-images.githubusercontent.com/2306947/106608567-d8996a80-6564-11eb-930f-fc8a9728d410.jpg)
j'ai toujours le bouton rouge "Recevoir l'invitation" pour slack. c'est peux être juste ça le souci alors.

**Comment by agallou** [comment]
@Kleinast nous venons d'effectuer une modification sur cette incohérence au niveau du statut de l'invitation. Est-ce que vous pourriez nous confirmer que le bouton renvoie bien au slack et que vous pouvez vous y connecter ?

**Comment by Kleinast** [comment]
Ah oui j'ai bien le bouton "Accéder" maintenant et qui m'ouvre bien sur le slack de l'afup c'est top merci beaucoup.

Je close l'issue du coup.

**Comment by SofLesc** [comment]
J'ai le même problème. Par contre quand j'accède à  http://afup-membres.slack.com/ il me dit que mon email n' a pas de compte sur cet espace de travail.
