### ISSUE TITLE
Impossible de telecharger/recevoir par mail les factures

### ISSUE THREAD

**Issue by pocky** [afup/web#1058]
Bonjour l'équipe,

J'ai renouvelé la cotisation de Vanoix cette après-midi. J'ai ensuite voulu recevoir par mail la facture pour la comptabilité du mois prochain et j'ai deux 403 lors du téléchargement et l'envoi de facture par mail.

C'est tout pour cette issue :heart:

**Comment by stakovicz** [comment]
D'après mes premières recherche, c'est que tu n'as pas le rôle `ROLE_COMPANY_MANAGER`.
Ça bloque dans la fonction [isCurrentUserAllowedToReadInvoice()](https://github.com/afup/web/blob/6ed6305416fe42bcba70ad45a4f04a1e7753bc91/sources/Afup/Association/Cotisations.php#L611)

**Comment by stakovicz** [comment]
Je vois une solution ça serait de modifier la fonction [verifierDroitManagerPersonneMorale()](https://github.com/afup/web/blob/278d9869ec247da2228a26db02b4b73243d43ac0/sources/Afup/Droits.php#L224) pour l'autoriser quand il n'y a qu'une personne physique liée à la société.

**Comment by stakovicz** [comment]
@agallou tu en pense quoi ?

**Comment by agallou** [comment]
Le souci vient effectivement du rôle `ROLE_COMPANY_MANAGER` qui manquait à l'époque.

Après une discussion sur slack on avait corrigé le problème le 20 avril 2021 en ajoutant ce rôle, mais en se distant qu'il y avait tout de même un souci : sans ce rôle ces lignes de cotisation n'auraient pas dues être affichées (a noter que j'aurais du reporter les informations dans l'issue).

Pour moi le problème se règle plus en n'affichant  les cotisations de la personne morale (attention, on peux avoir à la fois des cotisations de personnes morales et physique, il y a des cas à la marge comme celui-ci qui arrivent) que si on a le role ROLE_COMPANY_MANAGER (comme ça on aurait les mêmes conditions que pour le téléchargement/envoi par mail).

**Comment by stakovicz** [comment]
OK mais dans le cas de @pocky, comment il peut télécharger les factures pour sa société ?

**Comment by agallou** [comment]
@stakovicz dans son cas vu qu'on avait ajouté le rôle ROLE_COMPANY_MANAGER il arrive maintenant à télécharger les factures. Du coup il n'y a plus ce problème.

**Comment by stakovicz** [comment]
OK dons je vais simplement afficher les liens en fonction de ce rôle.

Je prépare ça.
