### ISSUE TITLE
Erreur lors de l'exécution de yarn

### ISSUE THREAD

**Issue by laurent35240** [afup/web#1087]
Lorsque l'on tente d'exécuter yarn, par exemple `yarn --version` on obtient cette erreur:
```
yarn install
/usr/share/yarn/lib/cli.js:46280
  let {
      ^

SyntaxError: Unexpected token {
```

Cela semble venir du fait que nodejs 6 n'est pas correctement installé lors du build docker.
Probablement lié a ce ticket https://github.com/nodesource/distributions/issues/1266 et aux problèmes récents de let's encrypt.

En attente pour le moment de la résolution du problème chez `nodesource/distributions`

**Comment by agallou** [comment]
on peux corriger cela en supprimant le certificat expiré, la modification est en PR ici : https://github.com/afup/web/pull/1088
