### ISSUE TITLE
Supprimer le chemin du template à la soumission d'une conférence

### ISSUE THREAD

**Issue by perrick** [afup/web#110]
Je viens d'ajouter une conférence pour le prochain Forum PHP 2015 et j'ai découvert que le chemin d'un template restait affiché en haut à gauche... Je ne pense pas que ce soit très compliqué à corriger ;-)
![img 2015-06-25 a 11 15 40](https://cloud.githubusercontent.com/assets/505024/8351208/e46252b6-1b2b-11e5-9a4d-b442b2509ff7.png)

**Comment by jacquesbh** [comment]
Closed by #116
