### ISSUE TITLE
Compléter les tests fonctionnels

### ISSUE THREAD

**Issue by agallou** [afup/web#1110]
Voici un état des lieux de ce qui est testé/reste à tester fonctionnellement : 

* afup.org
  * Admin
    * Membres
      * [x] Ajout/Suppression personne physique
      * [x] Gestion cotisaztion personne physique
      * [x] Export des 3 CSVs de personnes physiques
      * [x] Ajout personne morale
      * [x] Modification/Suppression personne morale
      * [x] Cotisation personne morale
      * [x] Liste des relances de cotisations
      * [x] Page de reporting
      * [x] Ajout d'un badge
      * [x] Association d'un badge à une personne physique
      * [x] Préparation d'une assemblé générale et listing
      * [x] Votes assemblée générale
    * Veille 
      * [x] Creation de campagne
      * [x] Liste des abonnés
      * [x] Historique
    * Site
      * [x] Création/modification/suppression feuille
      * [x] Création/modification/suppression rubrique
      * [x] Création/modification/suppression article
    * Evenement
      * [x] Création d'événement
      * [x] Création/modification/suppression de salle
      * [x] Suivi
      * [x] Ajout inscription
      * [x] 3 exports en CSV
      * [x] Virements en attente
      * [x] Token sponsor
      * [x] Mail de rappel de token sponsor
      * [x] Token visiteur
      * [x] Tarification
      * [x] Factures d'événement
      * [x] Conférences
      * [x] Vote visiteur
      * [x] Speakers
      * [x] Venue speakers
      * [x] Planning
      * [x] Github users
    * Trésorerie
      * [x] Devis
      * [x] Factures
      * [x] Journal
      * [x] Comptes banque
      * [x] Synthese événement
      * [x] Balance comptable
      * [x] Bilan
      * [x] Configuration
      * [x] Recherche comptable
    * Planète PHP
      * [x] Flux
      * [x] Billets
    * Divers
      * [x] Configuration planete PHP
      * [x] Configuration adresse
      * [x] Administrateurs
      * [x] Logs
      * [x] Sponsors/Partenaires
  * Event
    * CFP
      * [x] Faire une proposition au CFP
      * [x] Inviter un autre speaker au CFP
    * Proposition speaker
      * [x] Proposition speaker et mail
    * Billeterie
      * [x] Achat billet CB
      * [x] Retour CB Paybox
      * [x] Achat billet virement
      * [x] Achat billet tarif membre
    * Profil speaker
      * [x] Accès à la page
      * [x] Saisie des infos
  * Espace membres
    * [x] Accueil
    * [x] Gestion des utilisateurs personnes morales
    * [x] Gestion des coordonnées
    * [x] Cotisations
    * [x] Inscription veille
    * [x] Antenne la plus proche
    * [x] Présence AG
    * [x] Saisie infos fiche entreprise publique
  * Site public
    * [x] Home
    * [x] Actualités
    * [x] Adhésion personne physique
    * [x] Retour paybox adhésion personne physique
    * [x] Mail post adhésion personne physique
    * [x] Adhésion personne morale
    * [x] Retour paybox adhésion personne morale
    * [x] Mail post adhésion personne morale
    * [x] Listing Entreprises
* API pour event
  * [x] Planning
  * [x] Programmee
  * [x] Speakers
  * [x] Ical
* Planete PHP
  * [x] Flux RSS
  * [x] Listing article

**Comment by amenophis** [comment]
Ajout de tests sur l'historique des techletters: https://github.com/afup/web/pull/1114

**Comment by stakovicz** [comment]
Ajout de tests sur "Export des 3 CSVs de personnes physiques" #1121

**Comment by stakovicz** [comment]
J'avance sur les tests des Membres
- Modification/Suppression personne morale
- Cotisation personne morale
- ...

**Comment by stakovicz** [comment]
@agallou tu peux cocher ces 2 tests là :
- Préparation d'une assemblé générale et listing
- Votes assemblée générale

Ils sont gérés ici : 
- https://github.com/afup/web/blob/master/tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeeting.feature
- https://github.com/afup/web/blob/master/tests/behat/features/Admin/Members/GeneralMeeting/GeneralMeetingVotes.feature

**Comment by agallou** [comment]
@stakovicz ah oui, merci. c'est coché

**Comment by vinceAmstoutz** [comment]
J'avance sur les tests pour la partie évènement :
- [ ] Conférences
- [ ] Vote visiteur
- [ ] Planning

**Comment by stakovicz** [comment]
@afup/admins il faut que l'on cadre ces quelques testes :

Event > Billeterie : 
- Retour CB Paybox
- Achat billet virement
- Achat billet tarif membre

 Event > Profil speaker :
- Accès à la page
- Saisie des infos

Je ne vois pas trop comment les aborder.
On en discute à la réunion de jeudi.

**Comment by stakovicz** [comment]
Il n'en reste plus que 12 !!!

**Comment by stakovicz** [comment]
@agallou j'ai un problème pour tester l'adhésion d'une personne morale. Le formulaire utilise du JS pour générer les emails des membres attachés et il en faut au moins 1 pour passer la 1ère étape.

Est-ce que tu aurais une idée pour tester ça ?
https://github.com/afup/web/pull/1342/files#diff-0b4775a261cc6ade19cdcb072093158362476ab6269143a44aaad3251e87cf30R60

**Comment by stakovicz** [comment]
Ha oui et comment peut-on accéder au listing des entreprises depuis le site ?

**Comment by agallou** [comment]
@agallou là dessus c'est un peu comme la billeterie, à terme ça serait bien d'avoir dans ses cas un tag js, où on exécute les tests avec un driver chrome par exemple.
Mais ça risque d'être long cela. Pour l'adhésion personne morale que penses tu de reproduire en php dans un step behat cette partie ? https://github.com/afup/web/blob/8d877a29d932586f2348103dadf504b5c33ef326/app/Resources/views/site/company_membership/adhesion_entreprise.html.twig#L97-L112 (ce n'est pas idéal, mais probablement le plus simple pour le moment).

**Comment by agallou** [comment]
@stakovicz pour les membres, on y accède via l'url `/profile/company`. Dans l'admin il y a une feuille dans la "zone header" qui renvoie vers cette page.

![Screenshot 2023-11-15 at 08-12-27 Administration AFUP](https://github.com/afup/web/assets/320372/b57465dc-0033-4991-bd30-4748a13fdae3)

**Comment by stakovicz** [comment]
Pour l'adhésion personne morale je n'arrive pas à réinjecter l'HTML modifié dans Goutte/Mink/Behat afin de pouvoir soumettre le formulaire.

**Comment by stakovicz** [comment]
Héhé, j'ai trouvé une solution plus propre !

Je met un `CompanyMemberInvitation` par défaut dans le formulaire : 
https://github.com/afup/web/pull/1342/files#diff-7920f3dc9c518ec0b6042c5d1db3805b20787aea41c73894210f7f58db1c4bfdR57-R62

Comme ça, plus besoin de JS

**Comment by agallou** [comment]
@stakovicz super pour la solution avec les données par défaut. Effectivement j'avais commencé à creuser à part en devant étendre mink, je ne trouvais pas non plus de solution perenne.
