### ISSUE TITLE
Permettre d'administrer les questions pour l'AG

### ISSUE THREAD

**Issue by agallou** [afup/web#1111]
Actuellement il faut saisir les questions pour l'AG via des requêtes SQL. Il serait utile de pouvoir les ajouter/modifier/supprimer (s'il n'y a pas de vote) depuis le BO.

**Comment by stakovicz** [comment]
J'ai regardé, mais je ne vois du tout par quel bout le prendre ;-)

**Comment by agallou** [comment]
@stakovicz je vois pour mieux décrire l'issue dans la journée

**Comment by stakovicz** [comment]
Cool, mais rien ne presse

**Comment by agallou** [comment]
Sur `/admin/members/general_meeting_vote`,
quand on a une assemblée générale qui a été crée sur `/admin/members/general_meeting`.
on peux voir la liste des votes.

Par exemple on a cela : 
![Screenshot 2021-10-30 at 16-27-46 Administration AFUP](https://user-images.githubusercontent.com/320372/139537176-642ddaf1-5e84-420d-99e8-286f611993de.png)


Il existe déjà le mécanisme d'ouverture / fermeture de vote.

Par contre pour l'ajout on doit passer par des insertions via des requêtes SQL, dans la table `afup_assemblee_generale_question`.

Il serait donc utile de pouvoir ajouter/modifier des entrées dans cette table (seulement le champ `label`) pour une l'assemblée générale (identifiée via le champ `date`).

Du coup, dans la page `/admin/members/general_meeting_vote`, il faudrait en dessous du sélecteur d'AG, ajouter un bouton "Ajouter", qui va, permettre d'ajouter une question pour cette AG.
On arriverais sur un formulaire qui contiendrait seulement un input text afin de saisir le libellé.

@stakovicz tu vois mieux ce qu'il y aurais à faire ?

**Comment by stakovicz** [comment]
Oui, c'est beaucoup plus clair, merci. Je prend en charge cette issue !
