### ISSUE TITLE
Saisie multiple du profil de conférencier

### ISSUE THREAD

**Issue by SofLesc** [afup/web#1120]
Lors de la soumission d'une conférence à un CFP, le conférencier se voit obligé de remplir son profil conférencier même si il a déjà fait cela pour un autre CFP. Alors que, ensuite, le système reconnaît bien qu'il s'agit de la même personne et récupère les soumissions aux autres CFP.

**Comment by agallou** [comment]
Ces informations peuvent varier d'un événement à l'autre, on pourrait donc avoir récupérer les informations de la dernière participation de `afup_conferenciers`, et de préremplir les champs du formulaire, ce qui permettra de valider ces informations et saisir la nouvelle valeur dans `afup_conferenciers`.

Ajouter un message du type "Nous avons prérempli ce formulaire avec les informations de votre précédent soumission. Vous pouvez les éditer ou non selon votre souhait".

**Comment by magi-web** [comment]
@agallou  Je n'ai pas pu faire le lien avec l'adresse email car on ne la stocke pas dans la classe `GithubUser`. Par contre j'ai fait un lien avec l'id du github_user lié à d'autres lignes de `afup_conferenciers` :
``` SQL
SELECT afup_conferenciers.*
        FROM afup_conferenciers
        JOIN afup_forum ON (afup_forum.id = afup_conferenciers.id_forum)
        WHERE afup_conferenciers.id_forum != ?
        AND afup_conferenciers.user_github = ?
        GROUP BY afup_conferenciers.conferencier_id, afup_forum.date_debut
        ORDER BY afup_forum.date_debut DESC
        LIMIT 1
```
Est-ce que ça te convient ? 
Autre question : est-ce qu'on duplique la photo de profil ou on force les gens à uploader à nouveau la photo ? Si on duplique, il faut alors que je sauvegarde à la volée le speaker dupliqué car la photo est liée à l'id de la nouvelle entité Speaker. Qu'en dis-tu ?

**Comment by agallou** [comment]
@magi-web oui, ça me semble bien avec l'id github

On peut être forcer à uploder à nouveau la photo, autant rester simple pour le moment, ça aidera déjà de préremplir la plupart des champs texte (pour la photo ça voudrait dire la dupliquer, mais aussi présenter la photo qu'on va dupliquer au speaker pour permettre d'en uploader une autre. Autant faire ça dans une autre itération s'il y en a le besoin).

**Comment by agallou** [comment]
Suite à la PR #1152 le profil est maintenant prérempli.
