### ISSUE TITLE
Assemblée générale : permettre de modifier le texte descriptif

### ISSUE THREAD

**Issue by agallou** [afup/web#1128]
Lorsqu'on crée une assemblée générale on peux saisir du markdown pour ajouter des informations qui seront affichées dans la page dédiée de l'espace membre.

Par contre après création on ne peux pas modifier ce texte : on doit passer par une modification en base.

Il serait donc utile de pouvoir modifier la valeur de ce champ.

**Comment by agallou** [comment]
@stakovicz tu serait d'accord / ça t'intéresserais de prendre cette issue ?

**Comment by stakovicz** [comment]
Oui, pas de problème, je prends.
