### ISSUE TITLE
Ajouter numéro de téléphone sur la page profil speaker

### ISSUE THREAD

**Issue by agallou** [afup/web#1132]
Sur les pages de profil speaker il est possible de saisir les nuités d'hotel si l'information est activée, ainsi que la participation au repas des speaker.

Afin d'améliorer l'expérience speaker, il serait utile de leur demander un numéro de téléphone.

# Page profil speaker

Ajouter une section "Moyen de contact" dans la partie à gauche sur cette page : 
![Screenshot 2022-03-13 at 18-57-01 Call For Papers - Afup](https://user-images.githubusercontent.com/320372/158072702-82f1bf4c-6e0f-4837-824d-8008e6424911.png)

Avoir un input "numéro de téléphone" et un bouton de soumission.

Cet input remplira un nouveau champ `phone_number` dans la table "afup_conferenciers".

Un message explicatif indiquant pourquoi on demande le numéro (à définir) sera à indiquer.

# Admin - venue speaker

Ajouter aussi l'info de la présence du numéro sur le tableau "Venue speakers" : 
![Screenshot 2022-03-13 at 18-59-56 Administration AFUP](https://user-images.githubusercontent.com/320372/158072851-87a8ef8d-cc7f-4c31-adca-3574c94ce80a.png)

# Admin - édition speaker

Ajouter aussi ce champ de façon éditable sur la page modification d'un speaker : 

![Screenshot 2022-03-13 at 19-01-39 Administration AFUP](https://user-images.githubusercontent.com/320372/158072880-3d837432-2cec-4b2e-8a6d-6b28d4c0ae2b.png)

**Comment by vinceAmstoutz** [comment]
@magi-web puis-je récupérer le ticket ou vous êtes encore dessus ?

**Comment by agallou** [comment]
en fait le ticket a été réalisé ici : #1145 on ferme donc l'issue.
