### ISSUE TITLE
Bien charter l'adhésion personne physique

### ISSUE THREAD

**Issue by agallou** [afup/web#1139]
La page d'adhésion des personnes physiques ressemble à cela (https://afup.org/admin/register) :

![Screenshot 2022-03-16 at 08-20-30 Administration AFUP](https://user-images.githubusercontent.com/320372/158537115-9767c9e2-2f59-4a6d-938f-f7840ed10173.png)

La page d'adhésion des personnes morales ressemble elle à cela (https://afup.org/association/adherer/entreprise) : 

![Screenshot 2022-03-16 at 08-20-50 Afup - Association française des utilisateurs de PHP](https://user-images.githubusercontent.com/320372/158537151-bd07f5d8-2f72-4395-a24b-84c0f8f670c6.png)

C'est historique, cette page n'est pas chartée. Il faudrait la charter comme le reste du front (pour garder le contexte d'enête/footer notamment).

L'inscription est gérée ici : https://github.com/afup/web/blob/baea20261e4f8b31a699ae30719ad2246f087cae/sources/AppBundle/Controller/LegacyController.php#L73
Elle utilise smarty.

L'adhésion entreprise est géré elle ici : https://github.com/afup/web/blob/e76b355fc708abe3ec48ef1c09795299f748daa0/sources/AppBundle/Controller/MemberShipController.php#L54

Il faudrait passer le formulaire sur un form symfony afin de pouvoir basculer sur un template twig et pouvoir hériter du template `:admin/association/membership:_base.html.twig`.

**Comment by vinceAmstoutz** [comment]
@agallou que veut-tu dire par charter ?

**Comment by agallou** [comment]
@vinceAmstoutz par charter je veux dire que la page respecte la charte, le design d'afup.org. Qu'il y a ait entre autres, en haut les deux menus bleus, le footer et que le formulaire ressemble à celui des entreprises.

**Comment by Zarlokh** [comment]
Est-ce qu'on peut changer aussi l'url ou il faut pour x ou y raisons absolument conserver l'url actuelle ?

**Comment by agallou** [comment]
@Zarlokh on peux changer l'url, c'est même mieux, 
pour les adhésions entreprises c'est `https://afup.org/association/adherer/entreprise` on peux donc partir sur `https://afup.org/association/adherer/particulier` pour les particuliers (et on mettra en place une redirection coté apache, dans un htaccess).

**Comment by Zarlokh** [comment]
@agallou J'ai réussi à trouver le temps d'avancer sur le sujet
J'ai vu qu'il y a pas mal de valeur par défaut qui sont défini à la soumission du formulaire via des input hidden que j'ai normalement repris (faut que je regarde si les tests en place vérifie ça ou si il faut en faire)
Dans tous les cas, je regardais pour bien intégrer dans la charte et je me rends compte que lorsqu'un champs est invalide, on a un décalage de l'interface, champs pas en rouge, erreur pas en rouge etc...
![image](https://github.com/afup/web/assets/16246455/897bbe02-9bb0-46c1-b857-1c4e72418023)

Quand j'ai regardé sur le formulaire d'adhésion pour une entreprise, j'ai vu que c'est la même chose en réalité
![image](https://github.com/afup/web/assets/16246455/33be64bf-ae57-441a-9f5f-f425bef117cb)

Je me demandais si je laisse comme ça (semble être un form_theme a mettre de manière global pour l'ensemble du site sous sf donc peut-être une autre issue ?) ou si je corrige ce problème de manière unitaire sur ma page ?

**Comment by agallou** [comment]
@Zarlokh pour la vérification du numéro de téléphone j'aurais tendance à le faire dans une autre PR pour qu'on déploie ces changements au fur et à mesure
pour le souci de décalage, si tu arrives à le corriger dans cette PR sans que ça ne soit trop embêtant/ne prennes trop de temps, oui autant le faire maintenant, sinon on le fera plus tard vu que le problème est déjà présent

**Comment by agallou** [comment]
Traité dans la PR https://github.com/afup/web/pull/1516
