### ISSUE TITLE
Typo sur la page meetup

### ISSUE THREAD

**Issue by agallou** [afup/web#1142]
Sur la page https://afup.org/meetups/

Il est écrit "Retrouvez ici toutes les meetups"

Il y a une typo, il faudrait remplacer cela par "Retrouvez ici tous les meetups".

**Comment by Sidahmed-ben** [comment]
Hello @agallou  , I'm interested by the issue  can you assign it to me please  😀

**Comment by agallou** [comment]
C'est noté, merci, tu es maintenant assigné dessus.

**Comment by Sidahmed-ben** [comment]
d'accord je vais le faire !

**Comment by agallou** [comment]
Le correctif est en production. Merci @Sidahmed-ben

**Comment by Sidahmed-ben** [comment]
> Le correctif est en production. Merci @Sidahmed-ben

Je vous en prie 👍
