### ISSUE TITLE
Admin : supprimer "Exporter les inscriptions " dans "inscription > exports"

### ISSUE THREAD

**Issue by stakovicz** [afup/web#1147]
Cet export ne fonctionne pas.
Nous sommes systématiquement redirigé vers la page d'accueil de l'administration.
Il semblerait que le script `htdocs/pages/administration/forum_badge.php` ne semble pas exister.

Étapes pour reproduire : 
1. Aller sur la page Événements > Inscription ✅
2. Puis dans les Export choisir le 1er élément (Exporter les inscriptions) ✅
3. L'export ne se fait pas et on est redirigé vers `/admin/` ❌

**Comment by agallou** [comment]
On a perdu la fonctionnalité ici : https://github.com/afup/web/commit/5e4ca849ea10a5e05751676676d2dcbb3f0ccc1b#diff-dda7dcb3ebbc82be062810653f424e74759d0406b02dab1c4d4ae7135f96110cL159-L163

Où le controlleur gérait aussi l'export CSV.
Si on le refait il faudrait le faire différement.
La suppression a été effectuée en 2018.
On a déjà un export "Exporter les inscriptions pour les badges" qui permet de générer un CSV (mais peut prendre un peu de temps).

On peux supprimer donc ce lien "Exporter les inscriptions" dans "Exports" (et si jamais le besoin apparaitra d'avoir un export plus rapide on pourra reprendre l'export des badges sans les villes).
