### ISSUE TITLE
Rendre consistant les usages de "événement" et "évènement"

### ISSUE THREAD

**Issue by stakovicz** [afup/web#1148]
Il faudrait corriger les termes `événement`par `évènement`, non ?

**Comment by agallou** [comment]
Les deux se valent  :https://www.projet-voltaire.fr/culture-generale/evenement-evenement-orthographe-accent-aigu-grave/ 

Il y a une vingtaine d'occurences d'événements : https://github.com/afup/web/search?q=%C3%A9v%C3%A9nement
Et une dixaine d'évènements : https://github.com/afup/web/search?q=%C3%A9v%C3%A8nement

Du coup peu importe l'orthographe ici tant qu'elle est consistante à travers le projet.

(du coup j'aurais tendance à remplacer "évènements" par "événements", vu le volume de changements mais ça pourra peut être à l'apréciation de la personne qui prend l'issue).

**Comment by JulieNobody** [comment]
Je tente de prendre ce ticket

**Comment by JulieNobody** [comment]
PR : #1203
