### ISSUE TITLE
Rendre non obligatoire le descriptif lié aux lignes de tarification dans le BO

### ISSUE THREAD

**Issue by magi-web** [afup/web#1156]
Lorsqu'on édite la tarification d'un événement (ou lors d'une création), le champ "Descriptif" est obligatoire alors que le champ est nullable : 
![image](https://user-images.githubusercontent.com/662973/167698008-eb59f52d-635a-4efa-8e63-c16339f68216.png)

Il est souhaité de le rendre facultatif pour ne pas copier des libellés non voulus.

**Comment by agallou** [comment]
Supprimer la contrainte ici : https://github.com/afup/web/blob/077f515528730139d5af37447e41fe2b95b87503/sources/AppBundle/Association/Form/TicketEventType.php#L54

**Comment by seb37800** [comment]
@agallou @magi-web le champ n'est pas non null, cf db/migrations/20200424132500_tarif_event_description.php
Parce que sinon on se prend une jolie `QueryException`: 
`Column 'description' cannot be null`

**Comment by agallou** [comment]
@seb37800 effectivement il faudrait soit mettre une chaine vide dans la description (comme c'est le cas actuellement dans certains cas) ou rendre le champ nullable via une migration et y stocker NULL (ce qui semble plus propre)

**Comment by agallou** [comment]
oui, c'est fait, merci
