### ISSUE TITLE
Lien vers URL de paiement en BO pointe vers le mauvais événement

### ISSUE THREAD

**Issue by magi-web** [afup/web#1158]
Lorsqu'on va sur la section "Inscriptions", il existe un lien "URL de paiement" dans la colonne de "Statut de cotisation" qui pointe vers le mauvais événement. Tout pointe vers le PHP Tour Nantes. ([&forum=16](https://afup.org/pages/event-payment/?ref=ins-12898&forum=16))

![image](https://user-images.githubusercontent.com/662973/167705124-9895b64b-1302-441a-947e-4038c7f77932.png)

**Comment by vinceAmstoutz** [comment]
**TODO** : 
- [ ] Update selon les specs  [ici](https://github.com/afup/web/pull/1220#issuecomment-1304805161)
