### ISSUE TITLE
Impossible de se créer un compte 

### ISSUE THREAD

**Issue by nicosomb** [afup/web#117]
Bonjour, 

Impossible de me créer un compte ici : http://afup.org/pages/administration/index.php?page=inscription

J'ai l'erreur suivante : 
> Une erreur est survenue lors de la création de votre compte. Veuillez recommencer. Merci.

Tout semble bien renseigné (j'ai même essayé en réactivant le champ Login), mais pas possible d'adhérer. 

Nicolas

**Comment by jacquesbh** [comment]
Ton compte existe @nicosomb  sous le login `NicolasLoeuillet` ; Je pense que c'est pour ça que ça ne fonctionne pas. Ton email n'est sans doute plus bon par contre. Fais moi un mail sur tresorier [at] afup.org pour me donner ton nouvel email afin que je change tout ça.

Je m'occupe d'ajouter un peu de log pour que ça soit plus clair au niveau des erreurs car là c'est clair que c'est pourri comme message…

**Comment by nicosomb** [comment]
Fait. Merci du suivi.
