### ISSUE TITLE
Ajouter un lien d'évitement pour aller au contenu

### ISSUE THREAD

**Issue by agallou** [afup/web#1178]
Cela va permettre d'améliorer la navigation au clavier.

Cela doit être le premier élément dans le body, ici : https://github.com/afup/web/blob/0e970004c65855e67a4fda37a18c1399fd2eaeb3/app/Resources/views/base.html.twig#L29

Exemple :
```
<body>
  <a class="evitement" href="#contenu">Aller au contenu</a>
  […]
  <main rôle="main">
     <a id="contenu" tabindex="-1"></a>
     […]
  </main>
  […]
</body>
```

cf par exemple sur https://www.accede-web.com/notices/html-et-css/navigation-au-clavier/mettre-en-place-un-lien-devitement/

**Comment by cmourizard** [comment]
Cette feature était dans la PR https://github.com/afup/web/pull/1183, peut être fermer cette issue à la main du coup ?

**Comment by agallou** [comment]
ah, oui, merci. je la ferme aussi.
