### ISSUE TITLE
Changer les conditions pour le ticket personne ayant proposé une conférence

### ISSUE THREAD

**Issue by agallou** [afup/web#1193]
Actuellement pour bénéficier du tarif personne ayant proposé une conférence, il faut seulement avoir créé son profil speaker.

C'est un bug, en plus du profil speaker il faudrait vérifier si au moins un sujet a été soumis.

Modifier cette condition ici : https://github.com/afup/web/blob/109881ddca38dec5116eb7dd9426f478887ca7bb/sources/AppBundle/Event/Ticket/PurchaseTypeFactory.php#L64-L63 afin de vérifier si le speaker au au moins une conférence.

Les speakers sont liés à l'événement, du coup on a seulement besoin de vérifier que le speaker ait soumis un talk, et de fait, on ça vérifie qu'il ait soumis un talk à l'événement en question.

**Comment by stakovicz** [comment]
J'ai remarqué qu'il était possible de prendre toutes les places avec le trarif spécial CFP.
Je ne sais pas si c'est voulu, mais ce n'est pas limité à 1 seule place.

**Comment by stakovicz** [comment]
J'ai limité la sélection à une seule place au tarif spécial CFP.
