### ISSUE TITLE
Mauvais lien carousel event AFUP Day Lille 2023

### ISSUE THREAD

**Issue by vinceAmstoutz** [afup/web#1227]
Je ne sais pas si c'est en dur dans le code ou si c'est géré dans le BO @agallou.
Comme on peut le voir ci-dessous le lien est mauvais dans le carrousel https://event.afup.org/  pour ce bouton "Je découvre l'AFUP..." :
<img width="714" alt="image" src="https://user-images.githubusercontent.com/46444652/200594428-9e140a20-f85d-4337-8a5f-91a1da6583d0.png">

**Comment by vinceAmstoutz** [comment]
Si je ne me trompes pas le lien devrait être : https://event.afup.org/afup-day-2023-lille/.

**Comment by agallou** [comment]
c'est géré dans le BO du wordpress du projet https://github.com/afup/event

effectivement le lien ne devait pas être https://event.afup.org/forum-php-2022/infos-pratiques-forumphp2022/#accessibilite

le lien viens d'être corrigé, merci.
