### ISSUE TITLE
Espace site : CFP dans le slider quand CFP terminé

### ISSUE THREAD

**Issue by vinceAmstoutz** [afup/web#1231]
Je trouve quand dans cette situation que la slide CFP ne devrait pas être affichée.
Exemple : 

<img width="913" alt="Slide page d'acceuil AFUP Day 2023 CFP" src="https://user-images.githubusercontent.com/46444652/203747233-87a0854c-c3bc-47f0-9b1f-7aeedafc2229.png">
Puis quand on clique sur un des CFP :
<img width="670" alt="Page CFP Lyon AFUP Day 2023 CFP terminé quand on tente d'y accéder" src="https://user-images.githubusercontent.com/46444652/203747421-3d5af441-fa07-4693-ab09-1063534614f5.png">
Solution
---------
@agallou si tu es d'accord de masquer cette slide quand tous les CFP sont terminés et s'il y en a un sur les 2 de terminé par exemple celui de Lyon mais pas de Lille de masquer juste le bouton en question (je ne sais pas si ce dernier cas est utile).

TODO (suggestion)
---------------------
- [ ] Masquer la slide CFP quand tous les CFP du prochains évènement sont clôturés
- [ ] Masquer le bouton d'un CFP terminé dans la slide CFP si d'autres CFP pour le prochain évènement ne sont pas terminés

Je peux m'y assigner si besoin.

**Comment by agallou** [comment]
@vinceAmstoutz merci d'avoir remonté le souci.

cela correspond au wordpress (ce projet : https://github.com/afup/event), du coup ça s'administre dans l'admin du wordpress.  On viens de faire le changement dans celui-ci afin de supprimer le slide en question.
