### ISSUE TITLE
Ne plus utiliser l'API meetup afin de faire la synchronisation

### ISSUE THREAD

**Issue by agallou** [afup/web#1256]
Meetup.com a changé supprimé son API REST au profit d'une API graphQL, qui n'est disponible qu'avec un compte pro que nous n'avons pas.

Les meetups affichés sur afup.org ne sont donc plus à jour.

Il faudrait donc changer la façon dont les informations sont synchronisées.

Pour cela on peux utiliser les flux RSS des groupes meetups.

Par contre, vu qu'on ne veux pas seulement les meetups à venir, mais aussi ceux passer, on va devoir changer la façon dont on stocke ceux-ci.

Actuellement on parcourais l'API et envoyait les résultats sur algolia.

Il faudrait maintenant parcourir les flux RSS, stocker les contenus nouveaux ou modifier les existants en base dans une nouvelle table et ensuite faire l'indexation à partir de cette nouvelle table.

Il faut donc :

* créer une nouvelle table `meetup` contenant
** meetup_id
** title
** description
** date

a voir si on ajoute des champs : 
** venue_name
** venue_address_1
** venue_city

Les flux RSS sont accessibles à des url comme celles-ci : `https://www.meetup.com/fr-FR/afup-tours-php/events/rss/`

* dans une nouvelle commande
** appeler les flux RSS en utilisant le meetup_urlname dans l'officeCollection : https://github.com/afup/web/blob/3717053b46ae07d60095bb13d51a04151ac621c9/sources/AppBundle/Offices/OfficesCollection.php#L36
* parser ce flux et renseigner les infos dans la nouvelle table

voici un exemple de flux sur un event non AFUP
```
curl -L "https://www.meetup.com/fr-FR/apero-web-lyon/events/rss/"
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"><channel>
<title><![CDATA[Events - Apéro Web Lyon]]></title>
<link><![CDATA[http://www.meetup.com/apero-web-lyon/events/]]></link>
<description><![CDATA[Events - Apéro Web Lyon]]></description>
<copyright>Copyright 2002-2014 Meetup, Inc.</copyright>
<lastBuildDate>Thu, 19 Jan 2023 04:14:08 EST</lastBuildDate>
<managingEditor>support@meetup.com (Meetup)</managingEditor>
<item>
<title><![CDATA[Apéro Web Lyon - Janvier 2023]]></title>
<guid isPermaLink="true">https://www.meetup.com/apero-web-lyon/events/290870435/</guid>
<description><![CDATA[<p><img style="float:left; margin-right:4px" src="https://secure.meetupstatic.com/photos/event/b/3/b/7/event_499006007.jpeg" alt="photo" class="photo" />Apéro Web Lyon</p> <p><p>Bonne année et meilleurs vœux à tout le monde !</p> <p>Qui dit nouvel année dit nouveau lieu. C'est dans les locaux du cabinet de recrutement Effektiv que nous nous retrouveront le 23 janvier. Nos hôtes en profiterons pour nous faire une présentation et prendra un temps pour une Q&A sur le recrutement dans l'IT.</p> <p>\- Réaliser un produit SaaS\, les points essentiels \- Alexis Guerre<br/>\- Présentation\, Question&Réponse sur le recrutement dans l'IT \- Manon Bourdette\, Marguerite De Pury et Elise Faure</p> </p> <p>Lyon  69001 - France</p> <p>Monday, January 23 at 7:00 PM</p> <p>22</p> <p>https://www.meetup.com/apero-web-lyon/events/290870435/</p> ]]></description>
<pubDate>Thu, 19 Jan 2023 04:14:08 EST</pubDate>
</item>
</channel></rss>
```

malheureusement on est pas aidés, le title et link pourront être facilement récupérés car bien normés
l'id pourra être récupérés à partir du link
par contre pour la description la date et les infos sur le venue il faudrait les parser depuis la description ce qui n'est pas idéal.

a noter que c'est un peu la même chose avec l'ical

```
curl -L "https://www.meetup.com/fr-FR/apero-web-lyon/events/ical/"
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Meetup//RemoteApi//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-ORIGINAL-URL:https://www.meetup.com/fr-FR/apero-web-lyon/events/ical/
X-WR-CALNAME:Events - Apéro Web Lyon
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:Europe/Paris
TZURL:http://tzurl.org/zoneinfo-outlook/Europe/Paris
X-LIC-LOCATION:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20230121T202444Z
DTSTART;TZID=Europe/Paris:20230123T190000
DTEND;TZID=Europe/Paris:20230123T210000
STATUS:CONFIRMED
SUMMARY:Apéro Web Lyon - Janvier 2023
DESCRIPTION:Apéro Web Lyon\nMonday\, January 23 at 7:00 PM\n\nBonne année
  et meilleurs vœux à tout le monde ! Qui dit nouvel année dit nouveau li
 eu. C'est dans les locaux du cabinet de recrutement Effektiv que no...\n
 \nhttps://www.meetup.com/apero-web-lyon/events/290870435/
CLASS:PUBLIC
CREATED:20230111T141250Z
GEO:45.75;4.82
LOCATION:9 Rue du Garet (9 Rue du Garet\, Lyon\, France 69001)
URL:https://www.meetup.com/apero-web-lyon/events/290870435/
LAST-MODIFIED:20230119T091408Z
UID:event_290870435@meetup.com
END:VEVENT
END:VCALENDAR
```

mais que là on aurait pas à parser la date et que la location serait dans un champ dédié.
(pour récupérer la description il faudrait tout de même nettoyer le champ description)

vu qu'on a déjà la lib sabre/vobject dans le projet ça ne semble pas trop compliqué de le parser et pourrait potentiellement être plus simple à parser que la description du flux RSS (cf https://sabre.io/vobject/vcard/)

Dans tous les flux des tests unitaires là dessus seraient peut être pratiques.

* récupérer l'historique des meetups sur algolia et les insérer en base

* modifier la commande d'indexation des meetups pour avoir comme source la nouvelle table : https://github.com/afup/web/blob/cd4ff83bd83a620e8a51216236d6f3cfddfbd22f/sources/AppBundle/Indexation/Meetups/Runner.php#L51

* supprimer la dépendance au meetup client

(cf cet échange sur slack https://afup.slack.com/archives/C03L64VE9/p1673029737203359)

**Comment by vinceAmstoutz** [comment]
Hello,

J'ai commencé à prendre en main l'issue.

Avez-vous d'autres lien pour les flux RSS que celui que @agallou a mis dans le ticket ? 

<img src="https://user-images.githubusercontent.com/46444652/230841286-e03abaad-da1e-41f6-871f-9bd2626c80e7.png" alt="GitHub image 1" width="500">

<img src="https://user-images.githubusercontent.com/46444652/230841535-5a296088-6bc1-43c7-9548-5aa9301a91f5.png" alt="GitHub image 2" width="600">

**Comment by agallou** [comment]
Sur la version desktop à cette URL https://www.meetup.com/fr-FR/afup-lyon-php/events/calendar/

En bas de la page il y a les liens RSS/Atom/ical.

![Screenshot_20230410-105731_Firefox~2](https://user-images.githubusercontent.com/320372/230872201-74c77813-9adb-4c2e-b7b4-fadafdff6edd.jpg)

Par contre depuis que le ticket à été créé ils semblent ne plus fonctionner sans être connecté (ce qui perd de son intérêt).

A priori on est pas les seuls à avoir le souci https://wordpress.org/support/topic/trouble-with-meetup-calendars-please-read/
(Mais contrairement à l'article je ne pense pas que ça soit un souci de sécurité mais pour limiter la récupération des données et forcer à l'usage de leur api payante).

Je ne peux pas trop étudier plus les autres options pour le moment mais pourrais le faire après le milieu de la semaine.
