### ISSUE TITLE
Suppression mailings lists : supprimer le lien dans l'espace membres 1/2

### ISSUE THREAD

**Issue by agallou** [afup/web#1264]
Les mailings lists (emploi/ membres/entraide) ne sont plus utilisées (c'est maintenant Slack qui est utilisé). Cela est plus confusant qu'autre chose. Il faudrait donc dans un premier temps juste supprimer l'accès à celles-ci depuis l'espace membre (la page en question/synchronisation/libs utilisées pourra se faire dans un second temps). 

Supprimer ici les lien vers les listes de diffusion : https://github.com/afup/web/blob/9af616af58368aa612193cc672fd453b1e605ac4/app/Resources/views/site/member/index.html.twig#L89

Ainsi que l'item dans le menu : https://github.com/afup/web/blob/71968043201b66ae0ddcd8543401f25aff004eeb/app/Resources/views/admin/association/membership/_member_menu.html.twig#L25

**Comment by stakovicz** [comment]
Traitée par cette PR #1359
