### ISSUE TITLE
Migrer les comptes Google Analytics sur GA4

### ISSUE THREAD

**Issue by agallou** [afup/web#1274]
Migrer les comptes 
* du projet web
* d'event
* du baromètre
* des blogs d'antennes

**Comment by stakovicz** [comment]
Quand il n'y a pas de Google Analytics en place je l'ajoute avec Tarteaucitron ?

**Comment by agallou** [comment]
> Quand il n'y a pas de Google Analytics en place je l'ajoute avec Tarteaucitron ?

C'est sur quel projet qu'il n'y a pas le GA en place ?

**Comment by stakovicz** [comment]
J'étais sur le baromètre, mais j'ai mal cherché.
Tout va bien, j'avance.

**Comment by stakovicz** [comment]
Sur le site web de l'AFUP, il n'y a pas tarteaucitron.js mais il est possible d'activer le suivi global avec ces paramètres : `google_analytics_enabled` et `google_analytics_enabled`.

Est-ce que j'ajoute tarteaucitron.js ?

Ou est-ce que je me limite à la migration des conversions ?

Est-ce que tu peux m'ajouter au compte Google Analytics pour vérifier les données et migrer les conversions ?

**Comment by stakovicz** [comment]
Sur le site Event il semble que ce soit géré par Wrdpress directement, non ?

**Comment by agallou** [comment]
@stakovicz pour afup.org je ne penses pas qu'il y ait besoin d'ajouter tarteaucitron, autant reste iso on fonctionnel actuel et si ça ne prends pas trop de temps faire la conversion des migrations.

je viens de t'ajouter au GA (au final au niveau du compte pour bien avoir accès à toutes les propriétés), tu y a bien accès ?

Oui, pour event c'est géré par WordPress pour moi ça sort du cadre de ce ticket.

**Comment by stakovicz** [comment]
Entendu pour tarteaucitron.
Merci pour les accès, mais je ne vois que la propriété afup.org. Pas les autres.

**Comment by agallou** [comment]
@stakovicz je viens de corriger tes accès. Tu devrais avoir accès à toutes les propriétés maintenant. C'est bien le cas ?

**Comment by stakovicz** [comment]
C'est parfait ! Merci et bon courage pour le Forum :muscle:  :muscle:  :muscle:

**Comment by stakovicz** [comment]
Liste des MRs concernées :
- https://github.com/afup/web/pull/1321
- https://github.com/afup/barometre/pull/403
- https://github.com/afup/aix-marseille.afup.org/pull/20
- https://github.com/afup/bordeaux.afup.org/pull/3
- https://github.com/afup/limoges.afup.org/pull/5
- https://github.com/afup/nantes.afup.org/pull/1
- https://github.com/afup/rennes.afup.org/pull/1
- https://github.com/afup/toulouse.afup.org/pull/1
- https://github.com/afup/tours.afup.org/pull/1

**Comment by agallou** [comment]
Tous les trackings ont été mis à jour.
