### ISSUE TITLE
Ajouter une notion d'atelier au CFP

### ISSUE THREAD

**Issue by stakovicz** [afup/web#1289]
Dans la cas d'une proposition d'un CFP il faut laisser la possibilité au speaker d'indiquer s'il souhaites également faire un atelier.
Cet atelier est en plus du talk qui propose.

Pour cela, le speaker a accès à une case à cocher "Je propose de faire un atelier" et un champ texte pour décrire cet atelier.

**Comment by agallou** [comment]
@stakovicz oui, c'était quelquechose comme ça.
En faisant éventuellement en sorte que la zone de texte "résumé de l'atelier" ne soit affichée que si on coche la case.

Et en dessous de "Je propose un atelier", est-ce que ça serait possible d'afficher en petit le texte un "Lors de l’événement nous souhaitons proposer des ateliers d'une durée de 2 heures avec une vingtaine de participants et participantes au Forum PHP qui se seront inscrits et inscrites préalablement. Seulement les speakers sélectionné(e)s effectueraient un atelier. Cochez cette caser et renseignez la zone de texte ci-dessous si vous souhaitez proposer un atelier." ?
