### ISSUE TITLE
Ajout de tests fonctionnels pour la page d'accueil du site public

### ISSUE THREAD

**Issue by vinceAmstoutz** [afup/web#1325]
Tests Behat à ajouter dans le projet pour la page d'accueil du site public.

- Url : `/home`
- Template location : `app/Resources/views/site/home.html.twig`
- Controller : `sources/AppBundle/Controller/HomeController.php`

**Comment by stakovicz** [comment]
Traité dans cette PR: https://github.com/afup/web/pull/1342
