### ISSUE TITLE
Ajout de tests fonctionnels pour la partie adhésion des personnes morales du site public.

### ISSUE THREAD

**Issue by vinceAmstoutz** [afup/web#1327]
Tests Behat à ajouter dans le projet pour la partie adhésion des personnes morales du site public.

- Url : `/association/adherer/entreprise`
- Templates location : `app/Resources/views/site/company_membership`
- Controller : `sources/AppBundle/Controller/MemberShipController.php`

**Comment by stakovicz** [comment]
Traité dans cette PR: https://github.com/afup/web/pull/1342
