### ISSUE TITLE
CFP - Ajour d'une case à cocher pour autoriser l'afup à transmettre le sujet aux antennes

### ISSUE THREAD

**Issue by cmourizard** [afup/web#1336]
Avoir une case à côcher sur le formulaire du CFP du genre "j'autorise l'AFUP à transmettre ma proposition de conférence aux antennes locales de l'AFUP, elles peuvent être intéressées aussi par votre conférence pour un événement local si vous avez l'occasion de vous en rapprocher" (formulation à affiner)

Eléments techniques :

- Formulaire à modifier : https://github.com/afup/web/blob/b78727a1f89160175b5c04c1be653af38c2a7c5d/sources/AppBundle/Event/Form/TalkType.php#L75
- dans afup_conferenciers ajouter un tinyint(1) unsigned nullable, nommé par exemple has_allowed_to_sharing_with_local_offices

**Comment by agallou** [comment]
Traité dans la PR #1439
