### ISSUE TITLE
ETQ personne morale, quand je reçois une relance, je dois avoir une facture

### ISSUE THREAD

**Issue by paxal** [afup/web#139]
Les entreprises ont besoin d'une facture à payer pour renouveller la cotisation. Cette facture doit être envoyée en même temps que l'email de relance aux personnes morales.

**Comment by jacquesbh** [comment]
Je propose une facture proforma, ou alors un document autre… car avec le système actuel c'est un peu la galère.

Surtout que ça ne tient pas compte si on fait une facture de ceux qui ne veulent pas renouveler… qui dit facture dit paiement. Or dans ce cas…

**Comment by xavierleune** [comment]
La gestion du renouvellement des personnes morales ayant été revues, avec notamment l'interface leur permettant de le gérer, cette question n'est plus d'actualité
