### ISSUE TITLE
Passer la gestion des sessions en base

### ISSUE THREAD

**Issue by agallou** [afup/web#1415]
Se baser sur un système comme cela : https://symfony.com/doc/4.x/session.html#session-database-pdo

Cela va permettre de centraliser la gestion des sessions, qui sera utile quand on migrera sur Clever Cloud. On le fait ici ainsi sans complexifier la stack et ne devrait poser aucun souci vu notre usage.

**Comment by stakovicz** [comment]
Pourquoi il faut changer le stockage de session ?

Actuellement, il y a plein d'utilisation de $_SESSION dans le code. Est-ce que c'est gênant ?

**Comment by agallou** [comment]
@stakovicz c'était pour éviter des soucis sur le scaling horizontal, vraiment s'assurer qu'il n'y ait pas de souci de déconnexion (on peux aussi imaginer activer les sticky session, et n'avoir qu'une seule instance, mais centraliser la gestion des sessions me semblais plus sûr notamment lors des redéploiements)

**Comment by stakovicz** [comment]
OK c'est clair. Merci

**Comment by stakovicz** [comment]
Mergé et en PROD
