### ISSUE TITLE
Passer la gestion de la configuration historique sur le parameters.yml/config.yml

### ISSUE THREAD

**Issue by agallou** [afup/web#1416]
Migrer les différentes configurations de ce fichier pour finir par s'en passer : https://github.com/afup/web/blob/master/configs/application/config.php.dist

* bdd : utiliser pour source de données le container de symfony/valeurs du parameters.yml, quitte à conserver la variable $configuration['bdd'] mais qu'elle soit alimentée par le container
* divers : vérifier si c'est utilisé ou non, si c'est utilisé passer par des constantes
* mails : créer de nouvelles entrées dans le parameters.yml pour la config du SMTP. pour le reste mettre les valeurs en dur dans le code/constantes/dans le $configuration['mail'] en se basant sur les valeurs de prod.
* afup : conserver ces valeurs en dur en les ayant comparées à la configuration de prod
* rib : conserver ces valeurs en dur en les ayant comparées à la configuration de prod
* rib_ce : conserver ces valeurs en dur en les ayant comparées à la configuration de prod
* planete : passer par une constante
* site : vérifier si c'est utilisé, si ça l'est passer par une constante
* git : ça ne devrait plus être utilisé
* sympa : ça ne devrait plus être utilisé

Les changements peuvent éventuellement se faire au fur et à mesure dans plusieurs PRs.
Et à la fin il sera même possible de supprimer la page "configuration" dans l'admin.

**Comment by stakovicz** [comment]
Mergé et en PROD
