### ISSUE TITLE
[epic] Séparation de planete-php

### ISSUE THREAD

**Issue by stakovicz** [afup/web#1422]
Afin de pouvoir changer d'hébergeur pour Clever Cloud, nous avons besoin d'avoir des projets distinct pour chaque nom de domaine. Cela va facilité la migration et la maintenance.

Il faut donc sortir le code (front) de planete-php.fr dans un autre projet et mettre en place une API pour que ce dernier puisse récupérer les données.
On conserve le cron et l'administration dans le projet `afup/web`.

Cette epic permet de suivre ce projet de développement.

Étapes : 
1. créer un nouveau projet (`afup/planete-php-web` ?) et sortir le code (`/planete/*` et `/source/PlanetePHP/*`)
2. créer une API dans `afup/web` pour récupérer les données
3. brancher l'API et compléter les tests foncitonnels

Point d'attention, le flux RSS doit rester le même

**Comment by agallou** [comment]
cela a été fait via ce projet https://github.com/afup/planete/
