### ISSUE TITLE
Date erronée lors du paiement d'une cotisation par CB

### ISSUE THREAD

**Issue by jacquesbh** [afup/web#144]
## Faits

* Dernière cotisation : 2012-2013
* Paiement en novembre 2015 pour la cotisation 2015-2016

## Problème

La dernière cotisation payée enregistre une cotisation pour 2013-2014 au lieu de 2015-2016…
C'est plutôt problématique.

## Solution

Corriger le problème de date déjà.
Ensuite in serait bon d'informer le membre sur la page de paiement de sa cotisation des dates de sa prochaines cotisation s'il paie maintenant.

Par exemple, je sais que si un membre renouvelle sa cotisation moins d'un an après la fin de la précédente alors ça renouvelle à partir de la précédente (on considère que c'est un oubli) : sinon il est trop facile de faire ça et de ne payer qu'une année sur 2 pour avoir accès uniquement aux réductions sur les événements.

Il faudrait donc informer le membre dans un premier temps et corriger dans la foulée le cas de plus d'une année de décalage.

**Comment by xavierleune** [comment]
Déployé

**Comment by jacquesbh** [comment]
:clap:
