### ISSUE TITLE
ETQ administrateur je souhaite pouvoir supprimer un membre

### ISSUE THREAD

**Issue by jacquesbh** [afup/web#145]
- En tant que : Administrateur
- Je souhaite : Pouvoir supprimer un membre
- Afin de : le faire disparaître totalement de la base en ne gardant que le minimum légal.

Problème : Si on nous demande la suppression des données via la Loi Informatique et Liberté, on fait quoi ? :boom:

**Comment by jacquesbh** [comment]
En lien avec #56

**Comment by xavierleune** [comment]
Le minimum à conserver sur un compte (pour les factures notamment) sont: nom et prénom. Je propose donc qu'on anonymise l'ensemble des autres données (Adresse postale / Adresse email notamment) plutôt que de supprimer le compte de la base.
