### ISSUE TITLE
Envoyer les logs des crons sur New Relic

### ISSUE THREAD

**Issue by agallou** [afup/web#1455]

**Comment by stakovicz** [comment]
Actuellement en PROD, c'est un agent Newrelic qui est installé ?

Je vois qu'il y a un bundle Symfony Newrelic (ekino_new_relic) dans le projet mais je ne sais pas comment il est paramétré car il n'y a pas de `api_key` ou `license_key` dans la config.

Tu aurais un peu plus d'info pour ce ticket ?

**Comment by agallou** [comment]
oui, l'idée aurait été d'envoyer sur la partie log_management : https://newrelic.com/platform/log-management
et non pas sur la partie APM, gérée par le bundle d'ekino.

La partie log management peu recevoir des logs de plusieurs façon : https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/
Dont du Syslog, mais en TCP, qui ne semble vraiment pas idéal.

Du coup au final pour ce ticket j'aurais tendance à ne rien faire, laisser les logs s'écrire sur la sortie standard pour qu'ils arrivent sur la gestion des logs de Clever Cloud.

Et si vraiment ce n'est pas suffisant de voir les logs par ce moyen (qui devrait déjà être bien mieux qu'actuellement) on pourra mettre en place un drain vers New Relic : https://developers.clever-cloud.com/doc/administrate/log-management/#newrelic

Par contre plus tard (mais ce n'est pas utile pour la migration) il faudra peut être améliorer la sortie des logs des crons, mais c'est un autre sujet.

Donc finalement, je fermerais bien ce ticket. Qu'en penses tu ?

**Comment by stakovicz** [comment]
OK c'est plus clair.

On peut fermer et on avisera après la migration.
