### ISSUE TITLE
Ajouter des informations à propos du mode de transport sur la billeterie

### ISSUE THREAD

**Issue by agallou** [afup/web#1477]
Dans le cadre d'une certification nous allons devoir collecter des informations à propos de la venue des participants et participantes au Forum.

Pour cela nous allons devoir : 
* sur la table d'inscription au Forum (`afup_inscription_forum`),  :
   * ajouter deux champs
     * mode_transport_principal : VARCHAR(255), nullable
     * distance_parcourue, INT
   * ajouter la migration phinx
* ajouter dans la table `afup_forum` un champ transport_information_enabled en TINYINT NOT NULL
  * cela permettra notamment de permettre de mettre en prod ce ticket pendant que la billeterie de l'AFUP Day est ouverte et configurer en amont la billetterie du Forum et sera toujours utile pour les futurs AFUP Day.
* sur le tunnel de vente, rendre ces champs visibles
 *  ne le faire que si on a le champ transport_information_enabled qui a pour valeur 1
 * pour chaque personne venant au Forum on va devoir les indiquer
 * donc avant la saisie des tags afficher
   * "Dans le cadre de la certification LEAD (où on aura un lien sur "Certification LEAD"), nous devons vous demandez des informations à propos de votre venue, et-ce afin d'établir notre bilan carbone. Si vous n'êtes pas sûr de votre mode de transport, indiquez le plus probable.
   * Quelle est votre mode de transport ?
     * avec un sélecteur ayant pour valeurs
       * "Voiture thermique seul.e"
       * "Voiture thermique avec passager.e.s"
       * "Voiture électrique seul.e "
       * "Voiture électrique avec passager.e "
       * "Voiture hybride seul.e "
       * "Voiture hybride avec passager.e "
       * "Bus"
       * "Train"
       * "Avion - classe économie"
       * "Avion - classe business"
       * "Transports en commun"
       * "Vélo"
   * Quelle sera la distance parcourue (en km) ?
       * "<25"
      * "Entre 25 et 50"
      * "Entre 50 et 100"
      * "Entre 100 et 500"
      * "Entre 500 et 1000"
      * "> 1000"
   * ces deux champs sont obligatoires
   * si possible, quand on a plus d'une personne, après avoir affiché ces informations, afficher un lien "copier les informations de transport pour toutes les personnes", qui va recopier les informations saisies sur la première personne sur toutes les autres personnes du billet (ça peux aussi être fait dans une autre PR/un autre ticket)
* dans l'admin des événements, permettre d'activer le champ transport_information_enabled
* dans l'admin, sur la modification d'une inscription, afficher et permettre de modifier ces informations

**Comment by stakovicz** [comment]
Pour le champ `afup_inscription_forum.distance_parcourue` il est demandé un `INT` alors que dans les valeurs sont des tranches : 
-  "<25"
- "Entre 25 et 50"
- "Entre 50 et 100"
- "Entre 100 et 500"
- "Entre 500 et 1000"
- "> 1000"

Je stocke la valeur basse (par exemple pour "Entre 50 et 100" = `50`)
ou 
Je stocke change le type du champ pour un string et je stocke `Entre 50 et 100`
?

**Comment by agallou** [comment]
> Pour le champ `afup_inscription_forum.distance_parcourue` il est demandé un `INT` alors que dans les valeurs sont des tranches :
> 
>     * "<25"
> 
>     * "Entre 25 et 50"
> 
>     * "Entre 50 et 100"
> 
>     * "Entre 100 et 500"
> 
>     * "Entre 500 et 1000"
> 
>     * "> 1000"
> 
> 
> Je stocke la valeur basse (par exemple pour "Entre 50 et 100" = `50`) ou Je stocke change le type du champ pour un string et je stocke `Entre 50 et 100` ?

Je m'étais dit qu'on aurait pu avoir un id avec une CONST correspondant à chaque valeur, et qu'on pouvait potentiellement stocker ça du coup en INT. Mais si c'est plus simple à la saisie (et ça serait plus simple à l'usage pour les rapports), autant stocker en string avec "Entre 50 et 100".

**Comment by stakovicz** [comment]
OK je met en place des constantes, pas de problème

**Comment by stakovicz** [comment]
@agallou est-ce que tu aurais le lien vers la certification LEAD à mettre dans le texte ?

<img width="1065" alt="Capture d’écran 2024-04-23 à 21 23 33" src="https://github.com/afup/web/assets/83301974/4e36c9bc-4823-402c-87b1-3b0dc6bfd87d">

**Comment by agallou** [comment]
pour le lien ça serait celui-ci : https://event.afup.org/forum-php-2024/certification-lead/
