### ISSUE TITLE
Ajouter mécanisme de redirection de tous les mails vers un mail spécifique (pour la préprod)

### ISSUE THREAD

**Issue by agallou** [afup/web#1480]
Il faudrait pouvoir configurer une variable d'environnement où on saisi une adresse mail, et quand elle est définie, tous les mails envoyés seraient envoyés sur cette adresse mail présente dans la variable.

Cela permettra de mettre en place l'environnement de préproduction.

Si possible, si cette variable d'environnement est définie, préfixée l'objet par "[preprod] $to", où $to est le destinataire original

**Comment by tdutrion** [comment]
Question naïve, pourquoi ne pas utiliser un mailcatcher (saas ou self hosted) ?

**Comment by agallou** [comment]
Ce n'est pas une question naïve, c'est une très bonne remarque.
Suite à point mensuel du pôle outils, on a demandé si on pouvait bénéficier du plan Team gratuit sur https://mailtrap.io/pricing/ et est maintenant dans l'attente d'une réponse.

**Comment by agallou** [comment]
Mailtrap a accepté le compte Team NonProfit.

Du coup c''est configuré et ça fonctionne sur la future préprod : 
![Capture d’écran du 2024-06-17 22-06-20](https://github.com/afup/web/assets/320372/cf65f9e9-a20f-4883-999f-37399fb0f541)

Merci @tdutrion pour la suggestion.

**Comment by tdutrion** [comment]
C'est une très bonne nouvelle, ça simplifiera le developpement !
