### ISSUE TITLE
Les personnes morales paient toutes la cotisation minimale

### ISSUE THREAD

**Issue by paxal** [afup/web#149]
On demande aux personnes morales de payer 100€ quelque soit le nombre de personnes physiques rattachées à la personne morale.

Ces personnes morales devraient payer selon le tarif en vigueur, soit d'après l'article 8 des statuts de l'association :
> Personne morale : 100 (cent) euro / 3 membres

Je propose donc de modifier le montant à payer sur l'interface web et dans le mail de relance.

Ca correspond à ~1000€ par an (et j'imagine que c'est en fonction de l'assiduité du trésorier ;)).

**Comment by jacquesbh** [comment]
> Ca correspond à ~1000€ par an

Qu'entends-tu par là ?

**Comment by paxal** [comment]
On a des personnes morales qui paient 100€ alors qu'elles ont plus de 3 membres actifs enregistrés.
