### ISSUE TITLE
A chaque nouveau CFP, il faut refaire toute sa bio

### ISSUE THREAD

**Issue by lyrixx** [afup/web#1504]
Hello,

comme dit dans le titre, c'est un peu dommage de devoir tout refaire, alors que vous avez déjà toutes les informations.

**Comment by agallou** [comment]
Merci pour l'issue. En le mécanisme était censé être en place pour réremplir le formulaire avec les dernières informations précédentes, mais ne fonctionnait pas/plus. Cela vient d'être corrigé.
