### ISSUE TITLE
Page planning : permettre d'avoir deux talks sur le même créneau

### ISSUE THREAD

**Issue by agallou** [afup/web#1536]
Pour le Forum 2024 nous avons deux talks indiqués sur la même salle et la même heure (et-ce pour éviter d'avoir une 4ème et 5ème colonne sur le planning, qui le rendrait moins lisible) : https://event.afup.org/forum-php-2024/planning/ Un seul de ces talks est alors visible.

Il faudrait sur le planning ici : https://github.com/afup/web/blob/ef61f61bfd893a8424a9f087e90bdaf4684717fd/sources/AppBundle/Controller/BlogController.php#L81,

si on a deux évenements sur le même créneau de mettre 2 liens dans la même cellule, avec les libellés des deux talks.

**Comment by stakovicz** [comment]
Corrigé par https://github.com/afup/web/pull/1541 et https://github.com/afup/web/pull/1537
