### ISSUE TITLE
Conservation du format de fichier lors du redimensionnement

### ISSUE THREAD

**Issue by blackheaven** [afup/web#16]
Il faudrait conserver le format de fichier lors du redimensionnement des photos des intervenants : 
 * https://github.com/afup/web/blob/master/htdocs/pages/forumphp2013/appel-a-conferenciers.php#L117
 * https://github.com/afup/web/blob/master/htdocs/pages/administration/forum_conferenciers.php#L303

Le but étant d'éviter les problèmes de fond transparent : 
 * http://afup.org/pages/phptourlyon2014/conferenciers.php#810

Merci

**Comment by perrick** [comment]
Désolé mais c'est trop compliqué de gérer ce genre de demande. Surtout si on doit conserver l'historique sur plusieurs années... Donc on restera avec des JPG uniquement.
