### ISSUE TITLE
Erreur 500 une fois le paiement est termine

### ISSUE THREAD

**Issue by hachemsoft** [afup/web#172]
Bonjour 

Hier soir j ai payé ma cotisation et au moment de redirection de paybox vers afup y as eu une erreur 500
Du coup j ai recu mon ticket de paiement paybox
Mais pas le mail de welcome ;-) et sur mon espace abonné je ne vois ma cotisation 

Je veux le mail de bienvenue :)

**Comment by SylvG** [comment]
Bonjour,

Je viens d'avoir exactement le même problème.

**Comment by shyimg** [comment]
Bonjour,
Même problème pour moi ...

**Comment by Soldras** [comment]
Bonjour, 
le problemes est toujours d'actualité apparement ....

**Comment by mikaelrandy** [comment]
@shyimg @Soldras est-ce que vous pouvez prendre contact avec communication@afup.org pour que votre inscription soit validée ? ping @communicationafup
