### ISSUE TITLE
annuaire en ligne toujours accessible via google

### ISSUE THREAD

**Issue by communicationafup** [afup/web#175]
On a supprimé l'annuaire de notre site parce qu'il n'était plus entretenu / pas à jour. Cependant, une simple recherche avec le mot AFUP dans google le fait encore remonter dans les premiers résultats. peut-on régler ca ? http://www.afup.org/pages/annuaire/

**Comment by jacquesbh** [comment]
Suffit de supprimer le dossier et de mettre un .htaccess de redirection 👍  (ping @mikaelrandy, tu en penses quoi ?)

**Comment by mikaelrandy** [comment]
C'est exactement ce que j'étais parti pour faire
