### ISSUE TITLE
Erreur 500 lors du paiement de la cotisation

### ISSUE THREAD

**Issue by tristanbes** [afup/web#177]
Je viens de réaliser le paiement de ma cotisation.
Après paiement, le site afup renvoie une 500, le paiement n'a pas été enregistré sur le site, mais j'ai bien reçu le mail de paybox qui m'indique que j'ai bien payé. `C2016-120520161136-0-1646-BESSO-C08` (pseudo sur le site sf_tristanb)

**Comment by mikaelrandy** [comment]
Doublon avec #172 

Prenez contact avec communication@afup.org pour rétablir manuellement votre cotisation en attendant la correction du bug.

Dans tout les cas, merci d'avoir remonté le soucis ;)
