### ISSUE TITLE
Page pivot d'inscription

### ISSUE THREAD

**Issue by xavierleune** [afup/web#184]
La [page pivot d'inscription](http://afup.org/pages/site/?route=vie-associative/56/devenir-membre) actuelle est très triste et ne donne pas très envie d'aller plus loin. 

Par ailleurs elle contient trop de texte. nous devrions sérieusement envisager de supprimer les inscriptions papier / chèque qui sont trop compliquées à gérer.

Je mettrais 2 jolis boutons // CTA par exemple 
genre "Adhérer en tant que particulier" et "Adhérer en tant qu'entreprise"
avec un sous-titre "25€ - Adhésion pour 12 mois" // "100€ - Adhésion pour 12 mois pour 3 employés"

Poke @communicationafup qu'en penses-tu ?

**Comment by communicationafup** [comment]
@xavierleune complètement d'accord pour rafraichir / simplifier / rendre tout ca plus attractif !
