### ISSUE TITLE
Développement avec Ubuntu 16.04

### ISSUE THREAD

**Issue by mikaelkael** [afup/web#189]
Au 23/05/2016, il faut :
- appliquer le patch : http://stackoverflow.com/questions/36811863/cant-install-vagrant-plugins-in-ubuntu-16-04/36991648#36991648
- puis modifier Vagrantfile : https://github.com/chef/chef/issues/4948#issuecomment-220477913

**Comment by mikaelkael** [comment]
Pour le problème de chef, on a 8ddd542.

Pour le problème des plugins vagrant, on ne peut pas grand chose à notre niveau, à part amender `README.md`

**Comment by xavierleune** [comment]
Pour moi ça semble résolu avec les dernières versions de vagrant. Je suis sous 16.04 depuis quelques jours et tout semble ok. On peut fermer tu penses ?

**Comment by mikaelkael** [comment]
Le `vagrant provision` bloque actuellement, je ne peux pas confirmer. Je le corrige et je valide.

**Comment by xavierleune** [comment]
Tout est ok désormais normalement et le mode de dév à privilégier est plutôt docker
