### ISSUE TITLE
Envoie facture à partir du back [URGENT]

### ISSUE THREAD

**Issue by hellosct1** [afup/web#194]
On  ne peut pas utiliser facturation du menu Forum

et donc, je ne peux pas télécharger et envoyer les factures

http://afup.org/pages/administration/index.php?page=forum_facturation&id_forum=14

**Comment by xavierleune** [comment]
Ok

**Comment by jacquesbh** [comment]
À noter Christophe que les factures partent par email quand le client paie
en CB !

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

**Comment by jacquesbh** [comment]
Je veux dire par là que c'est automatique en théorie.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

2016-05-31 13:15 GMT+02:00 Jacques Bodin-Hullin <
j.bodinhullin@monsieurbiz.com>:
