### ISSUE TITLE
Problème lors du renouvellement de ma cotisation

### ISSUE THREAD

**Issue by BenoitLeveque** [afup/web#198]
Hello,

je viens de renouveler ma cotisation mais celle-ci n'apparait pas dans la page "Ma cotisation".

D'habitude j'envoi un mail au trésorier pour qu'il me corrige ça. mais il doit réellement y a avoir un problème avec mon compte.

**Comment by xavierleune** [comment]
Du coup il y a 2 issues pour ce soucis, je clos celle-ci pour que nous terminions la discussion sur #382
