### ISSUE TITLE
Créer une page dédiée avec la liste des antennes

### ISSUE THREAD

**Issue by xavierleune** [afup/web#200]
Voir avec @communicationafup pour les détails

**Comment by communicationafup** [comment]
Peut être peut-on fermer la rubrique Livre Blanc pour laisser la place à une rubrique Antennes Locales : on y explique brièvement le fonctionnement, la liste des antennes, comment les contacter... Est ce qu'on pourrait aussi ajouter (je sais pas dans quelle mesure c'est possible) un fil twitter qui ferait apparaitre les derniers tweets des différentes antennes?

**Comment by xavierleune** [comment]
Hello,
Pour agréger les tweets des antennes, c'est complètement possible. Il faudrait que tu crée une liste twitter à laquelle tu ajoutes tous les comptes des antennes. Ensuite on pourra créer un widget dessus sans problème!

Xavier.

**Comment by communicationafup** [comment]
hop https://twitter.com/afup/lists/antennes-afup

**Comment by xavierleune** [comment]
@communicationafup Je viens d'ajouter le widget twitter sur la page en question, ça ne rend pas super bien car le back office m'empêche de limiter sa hauteur (il fait un peu tout bugger) :disappointed:
