### ISSUE TITLE
Envoi des mails de confirmation des CFP

### ISSUE THREAD

**Issue by fferriere** [afup/web#205]
Le 26 Juillet, nous avons reçu un mail de non réception d'un courrier de confirmation de CFP comme on peut le voir ci-dessous.

```
<****@php.net>: host php-smtp2.php.net[72.52.91.12] said: 550 5.7.1 Looks
    like spam to me. (in reply to end of DATA command)

Final-Recipient: rfc822; ****@php.net
Original-Recipient: rfc822;****@php.net
Action: failed
Status: 5.7.1
Remote-MTA: dns; php-smtp2.php.net
Diagnostic-Code: smtp; 550 5.7.1 Looks like spam to me.
```

Est-ce possible de plugger cet envoi via mailchip/mandrill ?

**Comment by xavierleune** [comment]
Comme la nouvelle interface permet d'éditer ses propositions; on envoie plus de confirmation par mail.
