### ISSUE TITLE
Compte désactivé: meilleur message d'erreur à la connexion

### ISSUE THREAD

**Issue by xavierleune** [afup/web#206]
Lorsque le compte d'un membre est désactivé, il ne peut plus se connecter. Cependant le message d'erreur est semblable à celui d'une erreur dans le login et le mot de passe, ce qui génère beaucoup d'incompréhensions chez les membres.

Il faudrait donc dans un premier temps indiquer un message plus explicite pour ce cas particulier.

**Comment by mikaelrandy** [comment]
Je vais tenter de m'y mettre pour reprendre pied dans le BO

**Comment by jacquesbh** [comment]
Je pensais que j'avais justement amélioré ces messages… J'en suis même
persuadé :/

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

Le jeu. 28 juil. 2016 à 21:20, Mikael RANDY <notifications@github.com> a
écrit :

**Comment by mikaelrandy** [comment]
@jacquesbh je ne vois rien qui concerne la distinction entre une mauvaise connexion et un compte désactivé :/

**Comment by jacquesbh** [comment]
Ah oui non peut-être. Il y avait eu l'amélioration du message je crois,
c'est tout.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄

Le ven. 21 oct. 2016 à 05:03, Mikael RANDY <notifications@github.com> a
écrit :

**Comment by mikaelrandy** [comment]
@jacquesbh du coup, tu peux aller voir ma PR #230 pour le coup ;)
