### ISSUE TITLE
Process de réactivation de compte

### ISSUE THREAD

**Issue by xavierleune** [afup/web#207]
Lorsqu'un compte est désactivé pour cause de non paiement de cotisation, il n'y a aucun moyen pour récupérer un accès et payer sa cotisation sans intervention d'un membre de l'équipe. Il faut autoriser la connexion en restreignant l'accès uniquement au renouvellement de cotisation.

**Comment by mikaelrandy** [comment]
lié à #206

**Comment by xavierleune** [comment]
Yep l'idée c'est de passer #206 rapidement pour aiguiller les anciens membres et de passer #207 ensuite lorsque nous aurons un peu plus de temps

**Comment by xavierleune** [comment]
Le process n'est plus d'actualité avec la nouvelle gestion des relances
