### ISSUE TITLE
Mail de contact: favoriser l'inbox zendesk

### ISSUE THREAD

**Issue by xavierleune** [afup/web#211]
Il faudrait remplacer les différents mails de contact qu'on peut trouver sur le site par la version inbox: bonjour [ at ] afup (dot) org

**Comment by jacquesbh** [comment]
Hum… c'est pas fait ça si ?

Les emails sont pas changés en front.

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

Le mer. 7 sept. 2016 à 12:21, Xavier Leune <notifications@github.com> a
écrit :

**Comment by xavierleune** [comment]
j'ai fait la page de mentions légales, celle de contact, qu'est ce que j'ai zappé ?

**Comment by jacquesbh** [comment]
Il y en a [un peu partout au final](https://github.com/afup/web/search?utf8=%E2%9C%93&q=bureau%40afup.org)

**Comment by xavierleune** [comment]
je vais juste faire: htdocs/pages/administration/inscription.php  les anciennes éditions c'est pas grave à mon sens, ok pour toi ?

**Comment by jacquesbh** [comment]
Top
