### ISSUE TITLE
Relances automatiques: problème de dates

### ISSUE THREAD

**Issue by hellosct1** [afup/web#212]
Bonjour

Il y a un probleme au niveau des relances automatique

La procédure effectuée
- Sélection des personnes à relancer
- 1 clic envoyer
- L'envoie prend en compte les personnes supplémentaires

Identification du probleme
filtre avec la date : MMJJAAAA au lieu de JJMMAAAA
exemple : relance le 10 Aout 2016 (10082016) et envoie une relance aux personnes qui sont 02 Octobre 2016 (02102016)

Christophe

**Comment by xavierleune** [comment]
Gestion automatisée mise en oeuvre pour les personnes morales & les personnes physiques
