### ISSUE TITLE
Vagrant up ne fonctionne plus

### ISSUE THREAD

**Issue by xavierleune** [afup/web#213]
> $ vagrant up
> Bringing machine 'afup.dev' up with 'virtualbox' provider...
> ==> afup.dev: Box 'boxcutter/debian82' could not be found. Attempting to find and install...
>     afup.dev: Box Provider: virtualbox
>     afup.dev: Box Version: >= 0
> The box '["boxcutter/debian82"]' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/boxcutter/debian82"]
> Error: The requested URL returned error: 404 Not Found

**Comment by jacquesbh** [comment]
Il faudrait refaire le provisioning. Je fais ça dès que j'ai 20mn.

**Comment by jacquesbh** [comment]
(car chef-solo c'est dépassé et que ansible c'est plus pratique :p)

**Comment by mikaelrandy** [comment]
Est-ce que #226 ne corrigeais pas ce soucis ?

**Comment by xavierleune** [comment]
Bon on va se dire qu'on ferme celle-ci et si @jacquesbh veut migrer à ansible, qu'il se fasse plaisir :)
