### ISSUE TITLE
Récupération de mot de passe & compte désactivé

### ISSUE THREAD

**Issue by xavierleune** [afup/web#214]
Sur le process de récupération de mot de passe, lorsque le compte est en Inactif, on indique que tout va bien sur le formulaire de récupération de mot de passe.

Cependant il faudrait envoyer un mail au propriétaire du compte, indiquant qu'une procédure de récupération de mot de passe a été démarrée, mais que le compte est inactif et qu'il faut envoyer un mail à bonjour [@ ] afup.org afin de demander une réouverture du compte.

**Comment by jacquesbh** [comment]
Ou alors on réactive le compte pour lui ?

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

Le mar. 6 sept. 2016 à 16:16, Xavier Leune <notifications@github.com> a
écrit :

**Comment by xavierleune** [comment]
L'idée de cette issue c'est de pouvoir aller vite, après il faudrait faire #207

**Comment by jacquesbh** [comment]
Entre faire un mail et réactiver directement… heu… Comment te dire :p

**Comment by xavierleune** [comment]
c'est pas parce que le gars veut se connecter qu'il veut renouveler sa cotisation. Et comme on gère pas correctement l'état où le compte est actif mais la cotisation plus à jour, je pense pas que ça soit une bonne idée de réactiver le compte automatiquement.

**Comment by xavierleune** [comment]
Duplicate of #206
