### ISSUE TITLE
Privilégier bonjour@afup.org pour envoyer les mails

### ISSUE THREAD

**Issue by xavierleune** [afup/web#215]
Beaucoup de mails sont envoyés avec bureau@afup.org. Ca serait plus intéressant de les envoyer avec bonjour@afup.org pour faciliter la gestion des réponses

**Comment by jacquesbh** [comment]
Ça se change dans le config.php.

C'est changé en prod ❤️ .

**Comment by jacquesbh** [comment]
Tu closes quand tu veux si ça te convient.  @xavierleune

**Comment by xavierleune** [comment]
Merci ! :kiss:
