### ISSUE TITLE
Le retour CB semble ne plus fonctionner

### ISSUE THREAD

**Issue by jacquesbh** [afup/web#216]
On vient de nous contacter pour une facture non partie sur un paiement CB.
Effectivement l'inscription n'est pas validée.

Plusieurs inscriptions sont dans ce cas depuis le 12/09 (dernière CB validée… manuellement ou par IPN… no idea).

À checker donc ❗ 😢

**Comment by jacquesbh** [comment]
Retour du trésorier :

```
Lors du retour de paiement, paybox envoie un numéro de transaction et d'autorisation dans le back office
et cela passe en paiement validé en CB
et la facture est envoyée
Ces 2 champs ne sont plus remplis depuis le 13 septembre 2016
```

**Comment by xavierleune** [comment]
Les retours de paiement arrivent désormais d'une nouvelle IP (194.2.122.190) sans que nous n'ayons eu l'information. @hellosct1 tu as eu cette info de paybox ?

Je vais déjà ajouter l'ip dans la liste des IP autorisées. Je vais ensuite pouvoir faire du rattrapage à partir des access log apache

**Comment by xavierleune** [comment]
Rattrapage effectué
