### ISSUE TITLE
[WIP] CFP PHPTour Nantes 2017

### ISSUE THREAD

**Issue by xavierleune** [afup/web#225]
- [x] Page "d'accueil"
- [x] Corriger lien accueil
- [x] Verrouiller les votes lorsque le CFP est terminé
- [x] Visualisation des votes dans le BO
- [x] Transfert du CFP vers la nouvelle app
- [x] Corriger le .htaccess
- [x] .htaccess: gérer app.php vs app_dev.php
- [x] Skin
- [x] Vérifier sessions front & back
- [x] Stockage photo speaker: taille originale !
- [x] Stockage photo speaker: taille redimensionnée
- [x] Déploiement
- [x] Décompte jusqu'à la fin du CFP
- [x] Talk: Gérer le multi conférencier
- [x] Traductions

**Comment by xavierleune** [comment]
![Conférences pour lesquelles j'ai déjà voté](https://cloud.githubusercontent.com/assets/2320425/19532505/46c00b24-963c-11e6-8add-9420d876a60d.png)

![Mon espace conférencier](https://cloud.githubusercontent.com/assets/2320425/19532748/64eb788a-963d-11e6-9d7b-78fbb3a4b7e0.png)

**Comment by xavierleune** [comment]
WIP - en cours de calages :)

**Comment by jacquesbh** [comment]
👍👏

Jacques Bodin-Hullin

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

Le mer. 19 oct. 2016 à 20:50, Xavier Leune <notifications@github.com> a
écrit :

**Comment by xavierleune** [comment]
![Mon profil conférencier](https://cloud.githubusercontent.com/assets/2320425/19579552/90a4bd44-9721-11e6-8845-79219e6e6e42.png)

![Soumettre une conférence](https://cloud.githubusercontent.com/assets/2320425/19579561/a6b7aac4-9721-11e6-98c7-2da20a8c3594.png)

**Comment by xavierleune** [comment]
![Menu responsive](https://cloud.githubusercontent.com/assets/2320425/19626500/cf35d7e6-9933-11e6-80e0-102a0e4a6c8d.png)
![Page d'accueil](https://cloud.githubusercontent.com/assets/2320425/19626513/fecaaf40-9933-11e6-972c-e10cf8e36817.png)
