### ISSUE TITLE
Date de paiement sur les inscriptions aux events

### ISSUE THREAD

**Issue by webaaz** [afup/web#27]
Lors d'une inscriptions par CB pour un event, on note bien que le paiement est ok, mais pas la date du paiement qu'il faut ressaisir à la main.
Il faudrait automatiser ce processus.

**Comment by xavierleune** [comment]
@jacquesbh tu confirmes que c'est toujours d'actualité ?

**Comment by jacquesbh** [comment]
C'est bon depuis qu'on a le retour sur le site. C'est corrigé dans le code depuis début 2015 aussi. Oops :/
