### ISSUE TITLE
[IMP REDMINE] : Administration : gestion des relances par cron

### ISSUE THREAD

**Issue by mikaelkael** [afup/web#28]
Envoi du mail de relance à J-15, J+0, J+15, J+30, J+45 et J+60

Si pas de paiement à J+60, on désactive le membre

**Comment by jacquesbh** [comment]
Voir #77

Je pense qu'il vaut mieux garder la relance manuelle. Si on le fait 12 fois dans l'année c'est pas une tare.

**Comment by xavierleune** [comment]
Done
