### ISSUE TITLE
Installer graylog

### ISSUE THREAD

**Issue by xavierleune** [afup/web#287]
Ou tout autre outil de gestion de logs, afin de bénéficier d'une interface de visualisation des logs

**Comment by joelwurtz** [comment]
Je peux m'occuper de cela demain si tu veux @xavierleune avec une stack ELK (EHK pour être plus précis) si ca vous interesse ?

**Comment by xavierleune** [comment]
c'est quoi le H dans EHK ? Et n'est-ce pas un peu overkill vu le volume qu'on a ? Mais oui ça serait top que ce problème soit adressé !! :+1:

**Comment by joelwurtz** [comment]
Heka

**Comment by joelwurtz** [comment]
Enfin c'est deprecated, on peut parler de la solution la mieux adapté demain, pas le temps la pour un débat via github :D

**Comment by xavierleune** [comment]
Un logz.io a été paramétré
