### ISSUE TITLE
Erreur sur le renouvellement des cotisations

### ISSUE THREAD

**Issue by webaaz** [afup/web#3]
Le renouvellement ne se fait pas à la date du paiement pour éviter les petits malins qui ne payent qu'une fois sur deux. Ca c'est ok.

Cependant, un utilisateur qui n'était plus membre ou membre via une autre entité (entreprise par exemple), doit pouvoir repayer une cotisation à la date du paiement.

On peut dire que si il paye dans l'année de son renouvellement, on colle les dates à l'année qu'il aurait du payer. Si il a été plus d'un an inactif sans cotisation, c'est une nouvelle cotisation à la date du paiement.

**Comment by xavierleune** [comment]
Doublon avec cette issue #144
