### ISSUE TITLE
 [IMP REDMINE] : Revoir ses sujets forum postés

### ISSUE THREAD

**Issue by mikaelkael** [afup/web#31]
Hello,

Aujourd'hui, je voulais ajouter une session aux sessions que j'ai proposées pour le forum PHP.
Problème, je ne me souviens plus exactement de ce que j'ai proposé, et je suis dans l'incapacité de prendre connaissance des sujets que j'ai déja envoyés.

Petite idée d'amélioration : être capable de revoir (au moins relire), les sujets forum qu'on a déja proposés, avant le vote final et l'évènement.

**Comment by xavierleune** [comment]
Le titre de la conf & son contenu ont été ajoutés dans le mail de récap
