### ISSUE TITLE
 [IMP REDMINE] : pagination sur les news

### ISSUE THREAD

**Issue by mikaelkael** [afup/web#32]
je viens de me rendre compte que les news en home ne sont pas paginées et que cette liste semble afficher l'ensemble des news 

http://afup.org/pages/site/?route=06-actualit/9

il faudrait peut être paginer ces listes ? 

++

**Comment by paxal** [comment]
On peut clôturer cet issue ?

**Comment by mikaelkael** [comment]
Tout à fait
