### ISSUE TITLE
Redimensionnement de photo de speakers: gestion du PNG

### ISSUE THREAD

**Issue by xavierleune** [afup/web#324]
Il semblerait que notre gestion du PNG ne soit pas correcte, puisque les images PNG alpha se retrouvent avec un fond noir lorsque redimensionnées.

Image originale:
![Image originale](http://afup.org/uploads/speakers/16/originals/1623.png)
URL: http://afup.org/uploads/speakers/16/originals/1623.png

Image redimensionnée:
![Image redimensionnée](http://afup.org/uploads/speakers/16/thumbnails/1623.png)
Url: http://afup.org/uploads/speakers/16/thumbnails/1623.png

**Comment by joelwurtz** [comment]
Go mettre un thumbor ? https://github.com/thumbor/thumbor
 
C'est une application qui permet de crop facilement tes images de manière automatique, et le bonus ca fait de la detection de visage (et certainement autre ca utilise opencv derrière) et du coup tu peux automatiquement crop une image en centrant sur le visage de la personne.

**Comment by xavierleune** [comment]
C'est un peu lourd de gérer un service tiers pour 35 Conférenciers tous les
6 mois, non ? A choisir je préfère qu'on avance sur les logs 😉
