### ISSUE TITLE
 [IMP REDMINE] : Ajouter une pièce jointe dans les mailings

### ISSUE THREAD

**Issue by mikaelkael** [afup/web#33]
Permettre l'ajout d'un ou plusieurs fichiers (PDF par ex) lorsqu'on utilise l'outil de mailing du BO.
Exemples d'utilisation : envoyer le compte-rendu de l'AG, ajouter un document permettant d'illustrer le propos du mail...

**Comment by jacquesbh** [comment]
C'est bon si le mail est envoyé par Mandrill (avec `AFUP_Mail`).

On envoie la facture ainsi maintenant.
