### ISSUE TITLE
Erreur 500 retour page "Mot de passe perdu" après soumission

### ISSUE THREAD

**Issue by nicolascrequer** [afup/web#355]
Lors d'une demande d'un nouveau mot de passe sur la page "http://afup.org/admin/password", lors de la soumission on a une erreur 500 au lieu du message de confirmation d'envoi du mail avec le nouveau mot de passe. Le mail lui est bien envoyé  malgré l'erreur 500.

**Comment by xavierleune** [comment]
Merci pour le report ! J'ai pu reproduire et corriger le problème, je ne le reproduis plus en prod. Si tu rencontres encore un soucis, n'hésites pas à nous en faire part !

**Comment by nicolascrequer** [comment]
De rien je n'hésiterais pas si je vois d'autre bug :)
