### ISSUE TITLE
Espace Membre :  Lancer le calcul des oeuvres de l'AFUP (Erreur 500)

### ISSUE THREAD

**Issue by nicolascrequer** [afup/web#357]
Dans la partie "**Membres**" dans la rubrique "**Mon Compte -> Oeuvres** " ( http://afup.org/pages/administration/index.php?page=membre_oeuvres ) , quand on clique sur " Lancer le calcul des oeuvres de l'AFUP.", on a une erreur 500.

**Comment by xavierleune** [comment]
Merci de l'info !
