### ISSUE TITLE
Evenements: créer une PWA

### ISSUE THREAD

**Issue by xavierleune** [afup/web#377]
Celle-ci devra permettre de:

* Consulter la liste des sessions
* Créer son programme personnalisé
* Envoyer des notifications push avec la salle lorsqu'une conf sélectionnée va démarrer ou les détails de l'apéro communautaire
* Noter en live les confs (via joind.in via api ?) grâce à des notifications à la fin de chaque conf

**Comment by agallou** [comment]
* la liste des sesions est consultable (en étant connecté)  sur le site d'event : https://event.afup.org/afup-day-2022/programme/ . On a pas forcément eut le besoin d'avoir de version hors ligne
* Le planning personalisé peut être créé ici : https://afup.org/event/afupday2022lille/calendar
* pour les notes en live, un test sera fait avec openfeedback.

nous fermons donc ce ticket, si d'autres besoins sont remontent, on pourra le réouvrir / en créer un nouveau.
