### ISSUE TITLE
renouvellement cotisation

### ISSUE THREAD

**Issue by BenoitLeveque** [afup/web#382]
Bonjour,

j'ai renouveler ma cotisation à l'afup ce week-end (dimanche).

Je n'ai pas reçu de mail de confirmation (ni le mail de la banque) et mon compte ne s'est pas mis à jour correctement car la cotisation n'apparait pas.

Le paiement par contre lui a bien été fais.

PS: j'avais déjà eu des problème lors des 2 précédents renouvellement de cotisation (issue #198 et #63)

**Comment by fferriere** [comment]
Bonjour,

J'ai fait également fait mon renouvellement ce week-end, ma cotisation a bien été pris en compte (le prélèvement aussi) mais je n'ai pas reçu le mail de confirmation.

**Comment by xavierleune** [comment]
Hello @BenoitLeveque je vois que cette année il semblerait que ton renouvellement se soit effectué correctement, peux-tu confirmer ? Si c'est le cas le bug dont tu souffrais a dû être réglé dans l'année.

Merci !

**Comment by BenoitLeveque** [comment]
Oui je confirme, le renouvellement est OK cette année, je ferme cette issue

**Comment by xavierleune** [comment]
Merveilleux 👌 Merci de ta réponse
