### ISSUE TITLE
[BUG affichage] CFP icon success dans le bouton de vote

### ISSUE THREAD

**Issue by metfan** [afup/web#396]
Dans le CFP après avoir soumis le formulaire via le bouton "Voter" l'icone svg de la class success sur le bouton ne s'affiche pas sur Firefox (53.0.3 32bit sur windows10) ça fonctionne très bien avec Chrome (et Edge)

Bonux: le logo Afup s'affiche mal sur Chrome (58), il est parfait sur Firefox et Edge

**Comment by xavierleune** [comment]
Hello,

Aurais-tu l'occasion de faire une capture du logo sous Chrome 58 ? Sous ubuntu et Chrome 58.0.3029.110 il s'affiche correctement,

Merci !

**Comment by metfan** [comment]
![afup_chrome](https://user-images.githubusercontent.com/1121867/27255306-044f6320-539c-11e7-9a3b-4bca7a30edff.PNG)

**Comment by metfan** [comment]
C'est chrome 59, il y a dû y avoir une maj.

**Comment by xavierleune** [comment]
Corrigé ce jour! Merci
