### ISSUE TITLE
Event: Expliciter l’intérêt du vote sur les conférences + Guidelines de rédaction

### ISSUE THREAD

**Issue by Grummfy** [afup/web#397]
Salut,
je pense que cela serait sympa de mettre un petit texte explicatif expliquant l'influence du vote sur les différentes propositions. Et peut-être une ou deux remarques sur ce qui importe a l'organisation afin d'aider les gens proposant des talk a être plus précis sur certains points ou non.

Qu'en pensez-vous?

**Comment by xavierleune** [comment]
Hello,

Ce sont clairement 2 bonnes idées que tu as là ! Malheureusement on a pas le temps de traiter ça efficacement pour cet event mais on le garde pour le prochain PHP Tour !
Je laisse l'issue ouverte afin d'y penser !

**Comment by xavierleune** [comment]
@ubermuda penses-tu que tu pourrais réfléchir à ce qu'il faudrait indiquer comme conseils aux votants & soumissionnaires ?

**Comment by ubermuda** [comment]
Je vais voir pour preparer un peu de wording sur le sujet dans la semaine

**Comment by xavierleune** [comment]
Poke @ubermuda :) :)

**Comment by ubermuda** [comment]
TU TE CALMES HEIN

**Comment by xavierleune** [comment]
ping pong poke @ubermuda

**Comment by xavierleune** [comment]
On devrait toujours avoir un @agallou avec soi !
