### ISSUE TITLE
Event: réduction sur ticketing

### ISSUE THREAD

**Issue by xavierleune** [afup/web#401]
Pouvoir gérer des coupons de réductions qui:

* Sont limités par le nombre d'usage
* Permettent d'appliquer une réduction en pourcentage
* S'appliquent uniquement sur les tarifs "publics" (pas sur les tarifs membres ni les tarifs early birds)

**Comment by agallou** [comment]
cf #598 : l'implémentation est différente, mais devrait permettre de répondre au besoin
