### ISSUE TITLE
Event: nouveau libellés de tarif sur facture

### ISSUE THREAD

**Issue by xavierleune** [afup/web#412]
affiche XXX sur les nouveaux types de facture

**Comment by jacquesbh** [comment]
et `XXX` serait quoi par exemple?

**Comment by xavierleune** [comment]
c'est ce qui est actuellement affiché au lieu du libellé

**Comment by xavierleune** [comment]
C'est dû au fait qu'au lieu d'utiliser les constantes globales & les variables globales pour stocker les tarifs c'est maintenant stocké en bdd
