### ISSUE TITLE
CFP: Photo de profil obligatoire lors d'une maj du profil

### ISSUE THREAD

**Issue by pocky** [afup/web#420]
Tout est dans le titre : le champ "photo de profil" est obligatoire même lorsqu'une photo est déjà présente.

**Comment by xavierleune** [comment]
Diantre ! Bon ça sera pas corrigé pour la fin du CFP mais on fixe ça pour Montpellier, promis :heart:

**Comment by pocky** [comment]
Vous êtes amour.
