### ISSUE TITLE
Permettre des titres en anglais sur le site event.afup.org

### ISSUE THREAD

**Issue by communicationafup** [afup/web#427]
Actuellement, les titres des rubriques sur la page d'accueil ne peuvent être qu'en une seule langue : du coup les titres sont en français sur la page en anglais. Si je les passe en anglais, ils apparaissent en anglais sur la page en français !

**Comment by agallou** [comment]
On a enlevé la version anglaise d'event.afup.org, je ferme donc cette issue.
