### ISSUE TITLE
forum PHP, tarif CFP et membre AFUP

### ISSUE THREAD

**Issue by plegall** [afup/web#437]
Bonjour,

Je viens de faire adhérer mon entreprise à l'AFUP. Notamment pour bénéficier d'un tarif préférentiel pour le forum PHP (mais pas que). En revanche, même connecté, sur la page de billeterie, je ne peux pas cocher la case "réservée membre AFUP". C'est ballot :-/

De plus, je vois qu'une PR est en cours pour faire bénéficier d'un tarif de 150€ pour les 2 jours si on a fait une CFP, voir https://github.com/afup/web/pull/431/files#diff-c3022b1594b467f0872d68ae56755397R7 (oui, j'ai lu le diff ;-) : c'est mon cas. Puis-je avois accès à ce tarif ?

A bientôt,

**Comment by xavierleune** [comment]
Bonjour Patrick,

Je vais vérifier s'il y a un soucis avec votre cotisation - certains paiements sont mal affectés de notre côté.
Pour le tarif pour les soumissionnaires au CFP, nous devons encore acter certains détails mais je t'invite à suivre la PR :) si elle est mergée alors ça sera tout bon !

**Comment by xavierleune** [comment]
En tous cas ta cotisation est désormais bien active, tu devrais être en mesure de cocher la case AFUP ! Pourrais-tu au moins vérifier que cela fonctionne bien ? Je laisse dans tous les cas cette issue ouverte tant que la question du tarif pour les soumissionnaires n'est pas tout à fait réglée.

**Comment by xavierleune** [comment]
Bonjour Pierrick, la PR #431 est passée en production !
La seule contrainte est qu'il est nécessaire d'avoir le même email déclaré sur github (car c'est celui utilisé en tant que conférencier grâce à la connexion par github) et dans le compte afup. En cas de soucis là dessus, n'hésites pas à nous contacter plutôt sur bonjour [at] afup.org.

Je me permets de clore ce ticket mais n'hésites pas si tu as encore besoin de nous !

Xavier

**Comment by plegall** [comment]
J'ai pu acheter ma place à 150€ :+1:

**Comment by xavierleune** [comment]
Parfait ! Merci du feedback !
