### ISSUE TITLE
Inscription aux listes de diffusion - KO

### ISSUE THREAD

**Issue by Pyrex-FWI** [afup/web#475]
![capture d ecran 2017-10-05 a 21 50 41](https://user-images.githubusercontent.com/422487/31249496-d42496f2-aa17-11e7-8cf3-0f3d6f0aca9e.png)

Impossible de s'abonner à une nouvelle liste.

**Comment by xavierleune** [comment]
Hello @Pyrex-FWI que se passe-t-il lorsque tu clique sur "m'inscrire" ?

**Comment by Pyrex-FWI** [comment]
@xavierleune , au clic, il y a un changement de couleur au niveau du bouton ce qui laisse à penser que l'action a été  bien validée.
Cependant, après une déconnexion / reconnexion les préférences sont à nouveau à l'état initial. Les préférences ne semblent pas être persistées

**Comment by xavierleune** [comment]
Ce point a été vu par email, le compte était dans un état incorrect et a été corrigé.

**Comment by Pyrex-FWI** [comment]
Merci pour le retour.
