### ISSUE TITLE
pas de permalien sur les news des phptours

### ISSUE THREAD

**Issue by omansour** [afup/web#48]
c'est pénalisant pour les relais vers les réseaux sociaux etc ..;

il faudrait avoir des liens depuis cette page : http://afup.org/pages/phptourlyon2014/

**Comment by paxal** [comment]
Salut,
Je propose des permaliens avec des ancres, ça devrait suffire et pas trop changer le site
https://github.com/paxal/web/compare/phptour_permalinks?expand=1
Cyril

**Comment by mikaelkael** [comment]
Pourquoi tu changes l'id de la rubrique (78 => 77) ?

2015-02-13 9:00 GMT+01:00 Cyril Pascal <notifications@github.com>:

**Comment by paxal** [comment]
Parce que je me suis trompé :)
