### ISSUE TITLE
Problème page Contact Forum PHP 2017 (Mauvaise URL)

### ISSUE THREAD

**Issue by nicolascrequer** [afup/web#491]
![image](https://user-images.githubusercontent.com/2781659/31319250-2db6b016-ac60-11e7-8bcc-73e822f73ec1.png)

Bonjour,

Il y a un problème d'url sur la page de "Contact" sur les pages du Forum PHP 2017 celle-ci pointe sur le PHP Tour de Nantes https://event.afup.org/phptournantes2017/contact/.

Nicolas **CREQUER**

**Comment by xavierleune** [comment]
Bonjour @nicolascrequer je te remercie de nous l'avoir signalé, c'est désormais corrigé ! La bonne url est donc celle-ci: https://event.afup.org/forumphp2017/contact/
