### ISSUE TITLE
Cotisations: revoir les règles de renouvellement ?

### ISSUE THREAD

**Issue by xavierleune** [afup/web#520]
Actuellement le renouvellement des cotisations avait été fait avec des règles un peu "bizarres".

Si la précédente cotisation s'est terminée depuis moins d'un an, alors la nouvelle cotisation vient "prolonger" la dernière. Dans le cas contraire, la cotisation est créée à la date actuelle (sauf si la cotisation en cours n'est pas encore finie, auquel cas ça vient se mettre à la suite).

Ce système est contre-intuitif et pas vraiment fair pour les membres qui auraient choisi de ne pas renouveler pendant 1 an.

Il y a donc 3 options possibles sur le renouvellement des cotisations:

1. Considérer que toutes les cotisations courent du 1er janvier au 31 décembre
2. Considérer que les cotisations courent toujours à partir de la date actuelle (sauf si cotisation toujours en cours, auquel cas on vient se mettre "à la suite" de la cotisation actuelle)
3. Rien changer (mais je suis pas trop fan)

Pouvez-vous donner votre avis sur cette issue ?

**Comment by metfan** [comment]
Je ne pense pas que la première solution soit intéressante pour les membres. Si une personne s'inscrit en fin d'année, il n'aura que quelques mois d'abonnement et sera donc lésé par rapport à quelqu'un qui aura payé sa cotisation en début d'année.

La deuxième solution me semble être la plus intéressante pour les membres.

**Comment by xavierleune** [comment]
De mon point de vue la solution 2 est également la plus adaptée.

**Comment by Simperfit** [comment]
Pour la 2 aussi 👍

**Comment by agallou** [comment]
je serais plutôt aussi pour la 2.

**Comment by xavierleune** [comment]
Merci pour vos retours, on part donc sur la solution 2, je lock cette issue.

**Comment by xavierleune** [comment]
Fait sur PR #525
