### ISSUE TITLE
Erreur 500 - Envoi cotisation/facture par email

### ISSUE THREAD

**Issue by nmariani** [afup/web#533]

**Comment by nmariani** [comment]
Dans mon compte j'ai une "Internal Server Error" à l'envoi de ma cotisation/facture par email.
Url : https://afup.org/pages/administration/index.php?page=membre_cotisation&action=envoyer_facture
Contexte : cotisation expirée

J'ai cloné le repo et installer l'environnement de dev avec Docker sans problème, je serai ravi de contribuer à l'occasion mais là il se pourrait fortement que ce soit dépendant de données spécifiques en base.
Ce sont d'anciennes cotisations, il est possible que ce soit pour cela.

Les access/error logs devraient fournir plus d'info sinon n'hésitez pas à me demander.

**Comment by xavierleune** [comment]
Hello, merci pour ton issue !
Je viens de regarder et ça semble assez simple à résoudre :) Le soucis vient de `Cotisations::envoyerFacture` qui utilise encore un vieux phpmailer.
Pour résoudre ce problème, il faudrait ajouter un second paramètre à la méthode `envoyerFacture`, qui sera une instance de `Afup\Site\Utils\Mail`. Pour récupérer cette instance, depuis membre_cotisation.php il te suffit de la récupérer depuis la couche symfony avec un `$this->get('app.mail')` et donc l'injecter en 2nd paramètre.
Ensuite pour effectuer l'envoi du mail en tant que tel, tu peux prendre exemple sur ce qui est fait dans `Facturation::envoyerFacture`, notamment pour la marche à suivre pour l'ajout du fichier en PJ. Pour le nom du template, tu peux t'appuyer directement sur la constante de classe `Mail::TEMPLATE_TRANSAC`.
Enfin il faudrait simplement penser à répercuter cette modification dans le fichier "htdocs/pages/administration/cotisations.php" afin de transmettre l'instance de Mail de la même manière lors de l'appel à "envoyerFacture".

Merci beaucoup pour ton aide !

**Comment by xavierleune** [comment]
Bonjour,
La pull request a été déployée, c'est désormais fonctionnel,

Bonne soirée,
