### ISSUE TITLE
Limiter le nombre de talk soumis par speakers

### ISSUE THREAD

**Issue by Zayon** [afup/web#536]
J'ai eu des retours sur le fait que voter pour les talks prends pas mal de temps. Effectivement quand on arrive à plus de 100 talks à lire ça se fait pas en 5min.

A coté de ça on voit des gens qui proposent 10 talks à eux seuls et ça fait beaucoup je trouve.

Je propose de limiter le nombre de talks soumis par speaker à 3-4.

J'ai fait quelques stats pour 65 conférenciers on a :

nombre de talks soumis | nombre de speakers | pourcentage | pourcentage cumulé
-- | -- | -- | --
1 | 34 | 52.30769231 | 52.30769231
2 | 14 | 21.53846154 | 73.84615385
3 | 6 | 9.230769231 | 83.07692308
4 | 6 | 9.230769231 | 92.30769231
5 | 2 | 3.076923077 | 95.38461538
6 | 1 | 1.538461538 | 96.92307692
7 | 1 | 1.538461538 | 98.46153846
8 | 0 | 0 | 98.46153846
9 | 0 | 0 | 98.46153846
10 | 1 | 1.538461538 | 100

Donc on voit qu'en limitant à 4 talks max, on garde plus de 90% des conférenciers.

**Comment by xavierleune** [comment]
Hello, je ne sais pas si c'est très pertinent de limiter aussi bas. Quelque part ça n'apporte pas grand chose de brider les speakers, alors qu'au final ça nous permet d'avoir une grande diversité de sujets. Si tu prends les CFP des autres confs, il est au contraire conseillé de poster pas mal de propositions. Par exemple la confoo conseille de mémoire de poster au moins 3 sujets différents.
En reprenant ton exemple on ne gagne que quelques pourcents et au final on peut passer à côté de quelques sujets sympas. Donc si on devait limiter, à mon sens c'est sur une valeur relativement haute, telle que 6 ou 8 sujets.

**Comment by agallou** [comment]
Nous n'allons pas limiter les sujets par speakers dans le CFP, je ferme donc l'issue.
