### ISSUE TITLE
Pas de feedback sur le vote cfp sous firefox

### ISSUE THREAD

**Issue by ubermuda** [afup/web#541]
Sous firefox le vote CFP ne donne pas de feedback comme quoi il a été pris en compte

L'appel Ajax renvoie une 200 ok avec un body `{"errors": []}`, et quand on refresh la page, le talk disparait, ce qui tend a indiquer le vote a bien été pris en compte

**Comment by xavierleune** [comment]
Corrigé, c'était un soucis de css, firefox ne supporte pas les svg inline en background, avec un coup de base64 ça fonctionne mieux

**Comment by ubermuda** [comment]
merci !

**Comment by ubermuda** [comment]
poke @lolautruche

**Comment by lolautruche** [comment]
👍
