### ISSUE TITLE
Event: commande billets après adhésion

### ISSUE THREAD

**Issue by xavierleune** [afup/web#551]
Il est nécessaire aujourd'hui de se déconnecter et se reconnecter afin de bénéficier des tarifs adhérents après adhésion. Il faudrait forcer un refresh des droits afin que cela fonctionne systématiquement, après adhésion (et lors de l'affichage de la page de commande).

**Comment by stakovicz** [comment]
Je viens de tester et il n'y a pas besoin de se déconnecter/reconnecter pour avoir accès au tarif AFUP.

**Comment by xavierleune** [comment]
Génial, merci @stakovicz 🙏
