### ISSUE TITLE
Ma cotisation − Administration AFUP  : Erreur sur le lien "Envoyer ma cotisation"

### ISSUE THREAD

**Issue by nicolascrequer** [afup/web#589]
![image](https://user-images.githubusercontent.com/2781659/36790649-d762a9da-1c95-11e8-8e24-a0c3c6808192.png)

Erreur 500 lors du clic sur un lien "Envoyer ma cotisation".

**Comment by xavierleune** [comment]
Bonjour @nicolascrequer 
Merci pour l'issue, c'est un doublon de la #533 que je vais corriger, je t'invite à suivre le statut sur cette autre issue.
Merci !
