### ISSUE TITLE
[Inscriptions] Prendre en compte les status des inscriptions

### ISSUE THREAD

**Issue by metalmumu** [afup/web#595]
Dans le backoffice, il faut prendre en en compte dans le nombre d'inscrits et dans l'export les uniquement les status suivants:
- Reglé
- Crée
Il ne faut donc pas prendre en compte les status
- annulé
- Erreur
-  refusé
....

**Comment by metalmumu** [comment]
idéalement il faudrait aussi supprimer le bouton supprimer

**Comment by agallou** [comment]
Cela va être corrigé dans le ticket #1131
