### ISSUE TITLE
Une adresse email avec un "+" cause une erreur dans la page Cotisation

### ISSUE THREAD

**Issue by willdurand** [afup/web#60]
Hello.

Une belle erreur `IBS_PORTEUR ne doit contenir que des tirets, @, etc.` s'affiche lorsque l'on s'inscrit (ou qu'on renseigne) un mail **valide** de la forme : `foo+bar@example.org`.

Cheers,
William

**Comment by mikaelkael** [comment]
Nous n'avons pas écrit cette lib. Elle semble avoir été fournie par Paybox. La corriger ne changera ps le problème de fond : à savoir que le gestionnaire de paiement Paybox n'accepte pas le caractère "+" dans les adresses emails.
