### ISSUE TITLE
Newsletter : 15 jours ou 2 mois ? 

### ISSUE THREAD

**Issue by benchti** [afup/web#620]
https://github.com/afup/web/blob/7b951f1c5b2b8c7dd85410ba90ca77a4cd35c897/app/Resources/views/site/techletter/index.html.twig#L19
https://github.com/afup/web/blob/4a687ef5587f2f706c760d7c19188a43e9e92cc8/app/Resources/views/site/base.html.twig#L417
![selection_999 080](https://user-images.githubusercontent.com/663816/40162951-ca5ba7c0-59b5-11e8-9df5-2d7676f153e1.png)

**Comment by agallou** [comment]
la newsletter dans le footer correspond à des informations sur l'actualité de l'afup et a lieu tous les deux mois (les projets/événements en cours et à venir au sein de l'association).

la veille de l'AFUP (celle dans le contenu de la page), est une sélection d'articles, de news, de projets de la part d'un pole dédié à l'AFUP afin de simplifier la veille technique aux membres inscrits à cette newsletter.

@benchti tu aurais tu idée sur comment rendre cela plus clair ?

**Comment by agallou** [comment]
Vu que les newsletters sont différentes, je ferme l'issue
Au besoin si tu veux @benchti tu pourra la réouvrir si celles-ci ne te semblent pas claires.

**Comment by benchti** [comment]
avec beaucoup de retard je viens de comprendre mon erreur : on clique sur le lien du haut je m'inscris et cela descend vers le bas et j'ai eu l'impression que cela faisait référence à la newsletter footer. 
je n'ai pas vu/lu le second "je m'inscris" 

Je propose donc de changer le texte 

`Tous les 15 jours, recevez les infos à ne pas rater, sélectionnées par les experts de l'AFUP.`

en 

`Tous les 15 jours, recevez les infos à ne pas rater, sélectionnées par les experts de l'AFUP. <b>Inscrivez vous ci-dessous</b>` 

Et supprimer le premier bouton "je m'inscris"
