### ISSUE TITLE
Mots de passes qui bloquent le compte

### ISSUE THREAD

**Issue by Korbeil** [afup/web#624]
Quand je change mon mot de passe par un nouveau de 32 caractères, mon compte est bloqué et impossible d'y accéder avec ce mot de passe.

Je reset le mot de passe et en met un de 10 caractères et cela fonctionne.

**Comment by agallou** [comment]
Le champ de saisie ne permet pas de saisir plus de 30 caractères : https://github.com/agallou/web/blob/fbfbf331954755860fe58a3d67ac97a709a0e319/htdocs/pages/administration/membre_coordonnees.php#L45-L46

Je pense qu'il faudrait enlever ces restrictions sur les deux champs (tout de façon, derrière on le hash, donc le hash fait toujours 32 caractères (une des améliorations à venir sera d'ailleurs d'améliorer ce hash))
