### ISSUE TITLE
Plus acces liste de diffusition, et derniere cotisation non visible dans l'espace membre

### ISSUE THREAD

**Issue by BenoitLeveque** [afup/web#63]
je n'ai de nouveau plus accès au liste de diffusion et ma cotisation est marqué comme expiré, alors que j'ai bien reçu un mail de confirmation de paiement le 11/06/2014.

**Comment by communicationafup** [comment]
Bonjour !

De mon côté je reçois des mails de membres qui demandent à renouveler leur
mot de passe pour s'identifier, et le nouveau mot de passe ne fonctionne
pas... Christophe Chervy par exemple est face à ce problème. Est-ce un
problème de cotisation non réglée ?
Merci à vous !
Amélie

Le 5 janvier 2015 13:23, Benoît Lévêque <notifications@github.com> a écrit :

> je n'ai de nouveau plus accès au liste de diffusion et ma cotisation est
> marqué comme expiré, alors que j'ai bien reçu un mail de confirmation de
> paiement le 11/06/2014.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afup/web/issues/63>.
>



-- 
---
Amélie Deffrennes
Coordinatrice nationale de l'AFUP
Association Française des Utilisateurs de PHP

@afup
www.facebook.com/fandelafup

**Comment by BenoitLeveque** [comment]
Mon problème de cotisation a bien été réglé par @webaaz, et je reçoit de nouveau les mails des mailings list, par contre je n'ai toujours pas la liste des listes de diffusion sur le site, je vais essayer de regarder dans le code si je trouve un problème

**Comment by mikaelkael** [comment]
Oui, je viens de migrer le serveur principal de l'AFUP. C'est un bug que j'ai remarqué ce WE. Je vais le corriger très rapidement.

**Comment by mikaelkael** [comment]
Corrigé par 93534c3fe622ffbd2284e0c470dc3d2df890ffa8
