### ISSUE TITLE
Rendre le champ "Société" optionnel lors de la création d'un profil de speaker

### ISSUE THREAD

**Issue by mnapoli** [afup/web#631]
![dexmxxrwaaa-zdc](https://user-images.githubusercontent.com/720328/40720438-090d2fdc-6417-11e8-8094-8f6b50295fc3.jpg)

Le champ est actuellement requis ☝️ ça serait cool si il pouvait être optionnel (pour ceux qui ne sont pas dans une entreprise. J'ai essayé de trouver le formulaire/template mais sans succès (et j'ai peur qu'il y ait aussi une contrainte forte en BDD).

**Comment by Korbeil** [comment]
Pourtant le champ est indiqué comme non requis dans la définition du form:
https://github.com/afup/web/blob/master/sources/AppBundle/Event/Form/SpeakerType.php#L25

Bug à creuser ?

**Comment by agallou** [comment]
@Korbeil ça viens de l'assertion NotBlank sur le champ company du speaker : 
https://github.com/afup/web/blob/d2c52bb194ca03124210c17ff63582e0b3c1c289/sources/AppBundle/Event/Model/Speaker.php#L57-L60

**Comment by mnapoli** [comment]
Youpi ! ❤️
