### ISSUE TITLE
Doublon dans le CFP ?

### ISSUE THREAD

**Issue by Korbeil** [afup/web#636]
Hello !

J'étais en train de voter pour les conférences du CFP et j'ai vu deux fois la même conférence.

A la première page:
![capture d ecran 2018-06-12 a 10 15 39](https://user-images.githubusercontent.com/944409/41278206-977f5828-6e29-11e8-8874-7db64d7a9715.png)

Puis à la troisième page:
![capture d ecran 2018-06-12 a 10 15 02](https://user-images.githubusercontent.com/944409/41278178-80a59eaa-6e29-11e8-8145-e533b5746904.png)

J'ai pu remarqué que les deux conférences avait le même id dans le DOM:
![capture d ecran 2018-06-12 a 10 16 42](https://user-images.githubusercontent.com/944409/41278250-beab9628-6e29-11e8-8c6e-25ff56daa65b.png)

**Comment by mikaelrandy** [comment]
Je confirme qu'il n'y a qu'une seule conférence avec ce titre.

Est-ce que tu reproduisais à plusieurs reprises ?

**Comment by Korbeil** [comment]
Je ne le reproduit pas sur cette conférence aujourd'hui.

Je close du coup, je vous tiens au courant si je revois ça !
