### ISSUE TITLE
Supprimer la page "badges" sur le BO

### ISSUE THREAD

**Issue by agallou** [afup/web#645]
Dans le menu "Forum", il y a un item "badges".

Cette page n'est plus utilisée et pourrait être supprimée (ainsi que tout ce qui y est lié (les images par exemple si elles ne sont pas utilisées autre part ou des méthodes du modèle).

![capture d ecran 2018-06-30 a 19 52 54](https://user-images.githubusercontent.com/320372/42127803-5a3c84d4-7c9f-11e8-8672-b86c02ec3241.png)

**Comment by communicationafup** [comment]
J'espère qu'elles ne sont plus utilisées en effet ;)
AMélie

**Comment by klnjmm** [comment]
Je vois qu'il y a un label `good first issue`. Possible d'aider ou il faut une "formation" auparavant sur ce projet ?

**Comment by agallou** [comment]
Il faut commencer par instancier le projet, en suivant ce qu'il y a dans le README ici : https://github.com/afup/web/blob/master/README.md

Ensuite le contrôleur à supprimer est ici : https://github.com/afup/web/blob/68edbec847052d0bfae894209012d21acf90e8f9/htdocs/pages/administration/forum_badge.php#L1 (où il faudra regarder ce qui est appelé/utilisé pour supprimer les méthodes désormais inutiles).
il y aura aussi le lien dans le menu du BO à supprimer.
https://github.com/afup/web/blob/59abbffaf557edc5d25126f84ece7c338eb1aba2/app/config/config.yml#L165-L165

Si tu souhaite on peux se faire un appel pour passer cela en revue/la mise en place de l'env de dev.
