### ISSUE TITLE
Supprimer l'inscription par papier

### ISSUE THREAD

**Issue by webaaz** [afup/web#65]
Il faudrait supprimer la possibilité de s'inscrire par papier. 
L'utilisateur doit pouvoir juste envoyer son chèque par papier, mais doit saisir les infos en ligne !

**Comment by jacquesbh** [comment]
J'ai fait un google form et modifié la page d'inscription avec le lien vers celui-ci.

**Comment by jacquesbh** [comment]
Je précise : uniquement pour les entreprises.
Si un développeur ne veut pas s'inscrire en ligne je ne vais pas l'en empêcher… et c'est surtout beaucoup moins courant !
