### ISSUE TITLE
Veille de l'afup: Gestion UTF-8

### ISSUE THREAD

**Issue by xavierleune** [afup/web#651]
Lors de la récupération des infos d'une url, les caractères UTF-8 ne sont pas gérés correctement.
Il faut vérifier l'encodage de la source et transcoder de manière appropriée, ou bien passer l'ensemble en UTF-8 côté veille - ce qui serait probablement + solide (mais à bien vérifier avec la synchro avec mailchimp dans ce cas)

**Comment by agallou** [comment]
On a pas eut de souci depuis la création de ce ticket lors de création de veilles.
De plus maintenant, on réécrit souvent les descriptions.
Du coup je ferme le ticket, si le problème se produit on pourra le réouvrir/en ouvrir un autre.
