### ISSUE TITLE
Merge de 2 adhésions

### ISSUE THREAD

**Issue by Fabex** [afup/web#663]
Bonjour,

J'ai actuellement 2 adhésions AFUP.
La première a été créé par mon ancienne société avec mon adresse perso. 
La deuxième par ma nouvelle société avec mon adresse pro.

Avant que ma nouvelle société me paye l'adhésion, j'ai changé mon adresse mail sur mon premier compte, en me disant que ca permettra de faire matcher les emails et donc d'éviter de me recréer un compte. 
Du coup l'adhésion c'est bien passé et j'ai recu un mail comme quoi ma société avait créé un compte pour moi. J'ai donc renseigné mon adresse mail pro mais du coup ca m'a dis que un compte existait déjà avec cet email.
J'ai donc rechangé mon 1er compte en remettant mon adresse perso et j'ai pu ainsi finalisé l'inscription de l'invitation de ma nouvelle boite avec mon adresse pro.

Du coup je me demande si il serait envisageable de pouvoir merge 2 comptes, parce que du coup je me retrouve avec 2 voix.

**Comment by mikaelrandy** [comment]
Il n'est aujourd'hui pas possible de merger 2 comptes.
Actuellement, tu disposes de 2 comptes, tout 2 rattachés à des personnes morales.
Tu n'as donc pas de vote, puisque c'est la personne morale qui dispose d'un vote.

Est-ce que tu veux que je désactive l'un des 2 comptes ?

**Comment by agallou** [comment]
Si le problème se reproduit nous évaluerons la possibilité d'une évolution.
En attendant (et vu l'ancienneté du ticket), nous fermons celui-ci.
(A noter, pour la fusion de comptes entreprise, il y a ce ticket : #369 )
