### ISSUE TITLE
Expliciter condition adhésion pour tarif membre

### ISSUE THREAD

**Issue by mikaelrandy** [afup/web#681]
Dans la [page de réservation des billets pour les évènements](https://afup.org/event/forumphp2018/tickets?_locale=fr), il n'est pas clair que l'adhésion doit être valide *au moment de l'évènement*.

<img width="638" alt="capture d ecran 2018-10-17 a 12 43 23" src="https://user-images.githubusercontent.com/187703/47081246-62915e00-d20a-11e8-92e0-65223c3d118f.png">

Il faudrait plusieurs évolutions : 
- [x] Expliciter ce fait dans la page
- [x] Pour les membres dont la cotisation sera expirée au moment de l'évènement, ajouter un warning "Attention, votre cotisation n'étant valide que jusqu'au XX, pensez à renouveler votre adhésion avant l'évènement".
- [ ] Ajouter une fonction de rappel +/- automatique qui permet de relancer les membres.

**Comment by xavierleune** [comment]
Euh https://github.com/afup/web/blob/master/app/Resources/views/event/ticket/ticket.html.twig#L67 ça me semble plutôt clair lorsqu'on est dans un cas concerné

**Comment by mikaelrandy** [comment]
@xavierleune quand ta cotisation est valide le jour d'achat, tu n'as aucun warning. Regarde ma capture d'écran.

Par contre, ma seconde évolution est déjà faite, tu as raison.

**Comment by xavierleune** [comment]
Du coup je comprends pas bien la différence entre le point 1 et le point 2, étant donné que ceux qui ne seront pas membres à la date de l'événement ont l'information correspondante, non ?

**Comment by mikaelrandy** [comment]
Ah oui, en effet.
Si tu réserves à une date, et que la cotisation va expirer, on te le dis.
Du coup, le seul truc qui reste à faire, mais c'est du "Nice to have", c'est de faire un lien vers une CGV qui explique tout ça (et qui n'existe pas encore ;) )

**Comment by magi-web** [comment]
Le lien vers les CGV est présent dans la page de la billeterie. Nous ne voyons pas de tâches supplémentaires à ce ticket.
