### ISSUE TITLE
Création d'une veille : permettre de réordonner les items des veilles

### ISSUE THREAD

**Issue by agallou** [afup/web#698]
Actuellement il n'est pas possible de réordonner les items quand on crée une veille documentaire.

![capture du 2018-11-07 23-04-45](https://user-images.githubusercontent.com/320372/48163991-8adc1c00-e2e1-11e8-8754-8c4b6d9e9a7f.png)

Il serait donc utile dans la zone d'édition une news (la zone bleue à droite), d'avoir par exemple des boutons avec des flèches vers le haut/vers le bas pour baisser / monter la news (à voir s'il y a une autre solution pour cela).

Actuellement il faut supprimer/rajouter une news si on veux changer l'ordre, c'est peu pratique et fait perdre du temps (ou incite à ne pas le faire).

L'accès à cette page se fait en se connectant au BO (avec un compte admin ou un compte avec le rôle ROLE_VEILLE), en allant dans le menu "Veille" puis "Liste des campagnes". Sur la page qui s'affiche il faut ensuite cliquer sur le bouton "Créer cette techletter".

**Comment by helicos441** [comment]
Je prends l'issue.

**Comment by helicos441** [comment]
Le développement est fait de mon côté. J'attends que ma connexion Internet revienne (normalement demain ...) pour pousser le code et créer la pull request.

**Comment by helicos441** [comment]
Mis en production ce jour.
