### ISSUE TITLE
Page blanche sur l'envoi d'une facture par mail

### ISSUE THREAD

**Issue by webaaz** [afup/web#7]
Sur la liste des factures, le bouton envoyer par mail envoie sur une page blanche.
(lien du click : http://afup.org/pages/administration/index.php?page=compta_facture&action=envoyer_facture&ref=2014-9)

Le mail ne semble même pas avoir été envoyé

**Comment by perrick** [comment]
Je crois qu'il s'agissait d'un duplicate du bug #67.
