### ISSUE TITLE
Corriger les libellés sur les pages de CFP/Vote quand on ne peux que voter

### ISSUE THREAD

**Issue by agallou** [afup/web#701]
Sur des messages comme https://github.com/afup/web/pull/695/files/5359786e9039ae1521afc22719ead2ce77abad61#diff-a216747c80daaa1f2ea42dea4e83266b
Il est indiqué : 
`Pour pouvoir proposer une conférence ou voter, il vous sera nécessaire de vous authentifier avec Github.`
Pour le Forum on laisse généralement une semaine de plus après le CFP pour pouvoir vote. Le message n'est donc pas bon. Modifier celui-ci en fonction des dates de fin de vote/cfp, et regarder si il n'y a pas d'autres endroits impactés (comme le menu avec des liens pour proposer des confs)

(cf #695)

**Comment by macintoshplus** [comment]
Corrigé
