### ISSUE TITLE
Mettre à jour les textes de la rubrique "antennes" sur afup.org

### ISSUE THREAD

**Issue by communicationafup** [afup/web#713]
Les informations ne sont plus à jour pour les sous-rubriques "listes de antennes" et "élections" sur afup.org => antennes .
Les nouveaux textes sont disponibles ici : https://docs.google.com/document/d/1mdG3hXZ8H5FVYrsOxAFsH0rbdFdj6c0qHRCAJH6DMwI/edit?usp=sharing
merci !

**Comment by benoitpotier** [comment]
Bonjour,

Comment je m'assigne à l'issue?

Cordialement,

Benoît

**Comment by agallou** [comment]
un commentaire dans cette issue indiquant que tu travaille dessus suffira.

**Comment by helicos441** [comment]
Bonjour,
Je suis actuellement en train de traiter cette issue.
Cordialement,
pfcharles.

**Comment by helicos441** [comment]
La PR #738 a été ouverte pour pousser la modification.
pfcharles.
