### ISSUE TITLE
Page antennes : ajouter les liens vers les chaines Youtube

### ISSUE THREAD

**Issue by agallou** [afup/web#733]

**Comment by helicos441** [comment]
Bonjour,

Je prends en charge cette issue.

pfcharles

**Comment by agallou** [comment]
Merci.

On en parlait par mail, ça peux être pas mal de tenter de refondre la mise en page de cette liste d'antennes si on rajoute un nouveau lien (éventuellement tester une mise en page en colonnes comme https://afup.org/super-apero et des liens/boutons vers les différents sites externes)

voici la liste des chaines d'antennes:
* Reims : https://www.youtube.com/channel/UCmkMmVqrt7eI7YMZovew_xw
* Limoges : https://www.youtube.com/channel/UCPYMUpcC3b5zd-hVNGEWHAA
* Aix-Marseille : https://www.youtube.com/channel/UC77cQ1izl155u6Y8daMZYiA
* Rennes : https://www.youtube.com/channel/UCv1VGfqKhygjTOZkdVUWfpQ
* Hauts-de-France : https://www.youtube.com/channel/UCkMGtNcB-VeqMlQ9p2JMIKg

**Comment by helicos441** [comment]
OK, je vais voir pour faire une maquette de la nouvelle page dans un premier temps.
Je rajouterai les liens YT dans la BDD et dans la page ensuite.

**Comment by agallou** [comment]
ok. pour les liens youtube, en fait il n'y aurais même pas besoin de les mettre en base, il faudrait les rajouter ici : https://github.com/afup/web/blob/ae8372d4de20a9f368fa18f032a9d10a52ac6835/sources/AppBundle/Offices/OfficesCollection.php#L9

**Comment by helicos441** [comment]
Ah ok, comme j'avais vu qu'il y avait une table "afup_antennes" qui existait. C'est plus simple que prévu du coup :). Je ferai la modif d'ici la fin de la semaine je pense.

**Comment by helicos441** [comment]
Bonjour,

j'ai commencé la modification de cette issue. Concernant la mise en page de la liste, j'ai fait ceci:
![screenshot_liste_antennes](https://user-images.githubusercontent.com/30210744/54489450-7ff75080-48ac-11e9-9411-9e849f3052c8.png)

Qu'en pensez-vous ?

**Comment by agallou** [comment]
je me demande si vu le nombre de boutons on ne les inverserais pas et les passerais en blanc avec bordure bleue et remplis en bleus au survol (mais ça doit peut être pouvoir se tester / faire dans un second temps).

Dans l'ensemble c'est pas mal, ça devrait être plus compact que la version actuelle (surtout si on rajoute un nouveau type de lien).

Au niveau du texte et des icones, tu aurais possibilité de rajouter un peu d'espacement entre ceux-ci ? 

Pour le bouton meetup il y a une icone `fab fa-meetup icon` de disponible dans fontawesome (a voir si l'icone est dispo dans notre version)

Sur mobile on passe sur une antenne par ligne ?

**Comment by helicos441** [comment]
OK, je vais faire les modifs ce soir, je te tiens au courant. Je vais également tester sur mobile.

**Comment by helicos441** [comment]
J'ai réalisé les modifications suivantes:
![Screenshot_liste_antennes2](https://user-images.githubusercontent.com/30210744/54803061-3ae96a80-4c6e-11e9-92ba-6116c9ebde2e.png)
Pour la version mobile:
![Screenshot_liste_antennes3](https://user-images.githubusercontent.com/30210744/54803071-46d52c80-4c6e-11e9-868a-542535e29185.png)

**Comment by agallou** [comment]
ça me semble pas mal comme ça pour la version desktop (il y a juste le logo des meetups qui est manquant).

Pour la version mobile on peux peut être faire ça dans un second temps, mais on doit pouvoir peut être centrer horizontalement le tout, et faire en sorte que les boutons prennent toute la longueur (voire même qu'un bouton prenne 50% et qu'on ait 2 boutons par ligne).

**Comment by helicos441** [comment]
J'ai fait un pull request avec le logo meetup manquant.
Il me restera à améliorer l'affichage des boutons sur interface mobile.

**Comment by agallou** [comment]
traité dans le #753
