### ISSUE TITLE
[Docker]Erreur installation instance docker apachephp

### ISSUE THREAD

**Issue by helicos441** [afup/web#734]
Bonjour,

J'ai un souci de déploiement des images docker (commande make docker-up) sur un host Ubuntu 18.10 (docker 18.06.1-ce):

Step 10/17 : RUN apt-get update && apt-get install -y yarn
 ---> Using cache
 ---> 7707f41d2e33
Step 11/17 : ARG uid=1008
 ---> Using cache
 ---> 706d3289a3e9
Step 12/17 : ARG gid=1008
 ---> Using cache
 ---> 953771fc9cd0
Step 13/17 : RUN groupadd -g ${gid} localUser &&     useradd -l -u ${uid} -g ${gid} -m -s /bin/bash localUser &&     usermod -a -G www-data localUser &&     sed --in-place "s/User \${APACHE_RUN_USER}/User localUser/" /etc/apache2/apache2.conf &&     sed --in-place  "s/Group \${APACHE_RUN_GROUP}/Group localUser/" /etc/apache2/apache2.conf
 ---> Running in fea7aa2cccde
useradd: UID 0 is not unique
ERROR: Service 'apachephp' failed to build: The command '/bin/sh -c groupadd -g ${gid} localUser &&     useradd -l -u ${uid} -g ${gid} -m -s /bin/bash localUser &&     usermod -a -G www-data localUser &&     sed --in-place "s/User \${APACHE_RUN_USER}/User localUser/" /etc/apache2/apache2.conf &&     sed --in-place  "s/Group \${APACHE_RUN_GROUP}/Group localUser/" /etc/apache2/apache2.conf' returned a non-zero code: 4
make: *** [Makefile:20: var/logs/.docker-build] Error 1

Merci
pfcharles

**Comment by agallou** [comment]
bonjour,

je vois qu'il y a `useradd: UID 0 is not unique`, la commande `make docker-up` est lancée en root ?
(il ne faudrait pas la lancer en root, en rajoutant le user la lançant dans le groupe docker)

**Comment by helicos441** [comment]
Bonjour,

OK merci pour l'info. Après ajout de mon user dans le groupe docker et exécution des commandes make docker-up et make init avec mon user, tout est maintenant ok.

Merci.
pfcharles
