### ISSUE TITLE
Page post adhésion, paiement cotisation : ajouter un bouton pour tweeter à ce propos

### ISSUE THREAD

**Issue by agallou** [afup/web#735]

**Comment by communicationafup** [comment]
Pour les textes : 
pour le tweet : “Quelle bonne journée ! Je viens de régler ma cotisation à l’AFUP : une année supplémentaire de soutien à la communauté et d’avantages exclusifs autour de PHP !”
pour le texte à côté du bouton : “Je veux partager la nouvelle de mon adhésion à l’AFUP”

**Comment by helicos441** [comment]
bonjour,
je prends l'évolution.
PF

**Comment by helicos441** [comment]
J'ai effectué la modification (voir ici: [branche sur fork](https://github.com/helicos441/web/commit/8ecaa78ad6e5f1f93d7fa8919dbb42d1d225ecb7), je n'ai pas trouvé d'autres fichiers à modifier.
Commet puis-je tester cette modification (le bouton est fonctionnel dans une page web simple) dans le contexte d'une nouvelle cotisation en local ?

**Comment by agallou** [comment]
pour tester le paiement de la cotisation, tu peux mettre cette configuration dans  le fichier `configs/application/config.php`
```
$configuration['paybox']['site']='1999888';
$configuration['paybox']['rang']='99';
```
et ensuite utiliser un des numéros de carte de test qu'il y a sur : 
http://www1.paybox.com/wp-content/uploads/2017/08/Param%C3%A8tresTestVerifone_Paybox_V8.0_FR1.pdf

**Comment by helicos441** [comment]
OK merci. je testerai ça demain soir.

**Comment by helicos441** [comment]
Les tests sont ok. J'ai créé la PR 764 pour ajout sur le site.

**Comment by helicos441** [comment]
Merge et déploiement effectué ce jour.

**Comment by agallou** [comment]
cela a été traité dans le https://github.com/afup/web/pull/764, je ferme l'issue.
