### ISSUE TITLE
mail de confirmation de l'inscription à un event

### ISSUE THREAD

**Issue by communicationafup** [afup/web#74]
Lorsque la personne valide son inscription pour un cycle de conférence, elle reçoit par mail la confirmation de son inscription, et quelques informations : on la prévient qu'elle recevra la convocation quelques jours avant l'event, on lui donne les comptes Twitter et Facebook de l'AFUP, et quelques informations importantes (ex : au Luxembourg, il faut réserver sa chambre à l'avance). Je (Amélie) peux préparer ce texte.

**Comment by mikaelkael** [comment]
Oui STP. Je vais mettre en œuvre Mandrill pour cet envoi.

**Comment by communicationafup** [comment]
Mickaël,
Le mailing est prêt, la liste des hôtels a été ajoutée :
https://docs.google.com/document/d/1CnHZXr95PLzhGARDthuaOywJI1wMvUkvUh9GQHUTsrc/edit?usp=sharing

Bonne journée !
Amélie

Le 17 février 2015 09:10, Mickael Perraud <notifications@github.com> a
écrit :

> Oui STP. Je vais mettre en œuvre Mandrill pour cet envoi.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afup/web/issues/74#issuecomment-74631026>.
>



-- 
---
Amélie Deffrennes
Coordinatrice nationale de l'AFUP
Association Française des Utilisateurs de PHP

*PHP Tour Luxembourg 2015, les 12 et 13 mai à l'Abbaye de Neümunster :
www.phptour.org <http://www.phptour.org>*

@afup
www.facebook.com/fandelafup
