### ISSUE TITLE
Stocker physiquement les factures

### ISSUE THREAD

**Issue by mikaelrandy** [afup/web#755]
Actuellement, les factures sont générées à la volées à chaque demande de téléchargement.
Cela signifie que tout changement sur les données de la facture, ou de la configuration du site va conduire à la génération de différentes versions de la même facture, ce qui est illégal.

Il faudrait que les factures soient stockées physiquement à la première génération, et ne puisse pas être re-générées.

**Comment by agallou** [comment]
c'est un doublon du #736, je ferme l'issue.
