### ISSUE TITLE
Simplifier la saisie des articles

### ISSUE THREAD

**Issue by agallou** [afup/web#759]
Actuellement dans les articles on peux saisir 
* un surtitre
* un titre
* un descriptif
* un chapeau
* le contenu

au final on affiche seulement un teaser, un titre et un contenu

et on a des règles pour l'affichage du teaser:
https://github.com/afup/web/blob/441b0fe9e39216c96315039def1c451d67ea4501/sources/AppBundle/Site/Model/Article.php#L228
https://github.com/afup/web/blob/2c6fc26b8758a234b5fd710eb904459d02555bb7/sources/Afup/Corporate/Article.php#L110

a base de chapeau, description et s'il n'y en a pas, de fallback sur le contenu

on pourrait simplifier le modèle comme cela:
* un titre
* un chapeau
* le contenu

il faudrait donc faire un état des lieux de ce qu'on a en base et faire un script de migration afin de pouvoir supprimer ces champs inutiles (et en migrer le contenu dans celui seulement utile).

**Comment by macintoshplus** [comment]
Après avoir regarder, le contenu du chapeau est prioritaire sur la description.

La recherche des articles ayant chapeau et description donne 54 résultats (15 dans la catégorie 'actualite').

que faire du contenu du descriptif pour ces 54 articles ?

**Comment by agallou** [comment]
Pour la description il faudrait regarder si on a un chapeau, si on a un chapeau pour l'article à ce moment là on peux supprimer la description, si on a pas de chapeau il faudrait mettre la description dans le chapeau.

Le surtitre n'est plus utilisé on peux le supprimer.

(dans tous les cas avant suppression on dumpera/archivera la table).
