### ISSUE TITLE
ajouter une case "workshop" dans le formulaire de proposition d'une conférence

### ISSUE THREAD

**Issue by communicationafup** [afup/web#76]
Des conférenciers nous remontent le problème de la proposition d'un workshop. Actuellement le formulaire ne propose qu'un seul format, le format "conférence" (qu'il faut cocher pour pouvoir enregistrer sa conf). Peut-on ajouter le format "workshop" ?

**Comment by xavierleune** [comment]
Ticket pas clôturé mais fait depuis un moment:
![image](https://cloud.githubusercontent.com/assets/2320425/15518860/1d8a31e6-21ff-11e6-938f-652f63330643.png)
