### ISSUE TITLE
[Mail de relance d'adhésion] Ajout texte événement

### ISSUE THREAD

**Issue by jacquesbh** [afup/web#77]
Ça serait top de pouvoir ajouter un petit bloc de texte dans les emails de relance pour les adhésions.

Ainsi on pourrait promouvoir un événement par exemple.

Le champ serait en HTML (via éditeur wysiwyg?) idéalement.

Ça contredit un peu la demande #28 car si on fait une relance par cron on ne pourra pas personnaliser les emails.

Je suis d'avis de garder les relances manuelles. On le fait une fois par mois, c'est pas la mort :)

**Comment by xavierleune** [comment]
Et si on faisait un texte spinné automatiquement à partir de la table de forum ?

**Comment by xavierleune** [comment]
Etant donné que les mails ont été automatisés récemment, sauf à ce qu'on décide de spinner tout ça, je close l'issue pour le moment.
