### ISSUE TITLE
Migrer la saisie des coordonnées vers symfony

### ISSUE THREAD

**Issue by agallou** [afup/web#770]
Migrer la page de saisie des coordonnées (https://afup.org/pages/administration/index.php?page=membre_coordonnees), vers Symfony.

**Comment by helicos441** [comment]
Je prends.

**Comment by helicos441** [comment]
Voici quelques questions:
- Doit-on basculer cette page vers un contrôleur et formulaireSymfony ?
- Le contenu de la page reste identique ?
- Doit-on utiliser bootstrap pour le look-n-feel ?

**Comment by agallou** [comment]
* oui, l'idée serait de passer sur un controleur et formulaire symfony
* le contenu resterais identique (c'est une première étape pour avoir un nouvel espace membre et au passage continuer la bascule symfony)
* pour l'apparence tu dois pouvoir partir sur quelquechose comme sur https://afup.org/association/adherer/entreprise (ici pas besoin d'y passer trop de temps, on pourra faire une passe d'harmonisation dans un second temps)

**Comment by helicos441** [comment]
OK merci pour les informations. J'ai déjà repéré dans le code où se trouve la page actuelle. Je vois du coup pour commencer à développer ça !

**Comment by helicos441** [comment]
Mergé, mis en ligne et clos ce jour.
