### ISSUE TITLE
Erreur de chargement fichier styles.css

### ISSUE THREAD

**Issue by helicos441** [afup/web#787]
Bonjour,

J'ai reconstruit mon environnement ce matin à partir du master.
J'ai une erreur suivante avec le chargement d'un fichier styles.css dès que je veux charger la route /home:

![image](https://user-images.githubusercontent.com/30210744/56730808-21e64480-6759-11e9-800f-1f64118363fd.png)

Le fichier n'existe plus dans le dépôt mais un asset y fait toujours appel dans le fichier base.html.twig.

Merci !
pfcharles

**Comment by agallou** [comment]
un `./node_modules/webpack/bin/webpack.js` dans le container bash devrait résoudre le souci en générant le fichier (on passe maintenant par sass depuis le #772) (ou un make assets).

(ce make assets est effectué lors de l'init dans le Makefile)

ça corrige bien le problème ?

**Comment by helicos441** [comment]
C'est OK pour moi.
J'ai refait la commande "make init" et ça m'a corrigé l'erreur.
Merci !
