### ISSUE TITLE
Nommage des devis et factures

### ISSUE THREAD

**Issue by webaaz** [afup/web#8]
Certains devis et factures contiennent le nom du client et la date. Il serait intérressant d'ajouter aussi le numero de facture pour éviter les doublons.

Par ailleurs certaines pages (factures cotisation de mémoire) nomment encore les pdf : facture.pdf par exemple. Il faudrait généraliser

**Comment by xavierleune** [comment]
En cours

**Comment by paxal** [comment]
Résolu par 4f2cb1c
