### ISSUE TITLE
Probleme page CFP

### ISSUE THREAD

**Issue by hellosct1** [afup/web#803]
Bonjour

La page CFP pose un soucis de description quand l'appel à conférencier est terminé [1]

Il manque un message comme quoi l'appel à conférencier est clos.

Actuellement le message signale juste qu'on peut encore voter
Cela porte confusion pour les personnes qui veulent proposer un sujet supplémentaire

[1] https://afup.org/event/forumphp2019

Christophe

**Comment by macintoshplus** [comment]
Réalisé
