### ISSUE TITLE
Ajouter les infos Twitter + image pour la page About

### ISSUE THREAD

**Issue by communicationafup** [afup/web#81]
Peut-on ajouter les infos suivantes dans la page About s'il vous plait ?

 Follow #phptour on Twitter : @afup 

et faire apparaitre la photo suivante : 
http://upload.wikimedia.org/wikipedia/commons/1/1c/Centre_Culturel_de_Rencontre_Abbaye_de_Neum%C3%BCnster_(2266434485).jpg 

Merci !

**Comment by paxal** [comment]
Vu que l'event est passé je le passe en won't fix.
