### ISSUE TITLE
probleme line twitter (follow)

### ISSUE THREAD

**Issue by hellosct1** [afup/web#813]
Bonjour

La page des speakers affiche des erreurs au format twitter 
https://event.afup.org/forumphp2019/speakers/

On trouve 

* des lignes avec 2 @
Follow @@pierstoval 

* des lignes avec 1 url
Follow @https://twitter.com/JMLamodiere 

Merci pour la correction

**Comment by agallou** [comment]
Merci pour la remontée du problème, 

Pour les doubles arbases c'est quelque qui est géré par le widget.
Pour les urls complètes, on a effectivement un souci, qu'on va corriger via le #814 (et en le déployant sous peu)
