### ISSUE TITLE
Permettre de lier un conferencier a un compte github depuis le BO

### ISSUE THREAD

**Issue by agallou** [afup/web#827]
Actuellement pour les speakers invité(e)s on doit fait des insertions / update en base pour qu'ils/elles aient accès à leur page speaker.

Il serait pratique de pouvoir le faire dans le BO pour éviter cette manipulation à la main.

**Comment by amenophis** [comment]
Vas-y envoi les détails, je vais m'y coller !

**Comment by agallou** [comment]
cela a été traité dans la PR https://github.com/afup/web/pull/1092
