### ISSUE TITLE
Mettre en place un IPN pour Paybox

### ISSUE THREAD

**Issue by jacquesbh** [afup/web#84]
Voir page 21 : http://www1.paybox.com/wp-content/uploads/2014/02/ManuelIntegrationPayboxSystem_V6.2_FR.pdf

Il faut que le site soit capable de choper un retour automatique de Paybox afin de procéder à la validation d'un paiement même sans le retour de l'acheteur.

**Comment by jacquesbh** [comment]
Bon du coup je ferme cette demande.

On a un retour automatique depuis Paybox à présent, ça fait le taff.

**Comment by mikaelkael** [comment]
👍
