### ISSUE TITLE
les photos qu'uploadent les conférenciers ne sont pas enregistrées

### ISSUE THREAD

**Issue by communicationafup** [afup/web#86]
problème rencontré au Forum PHP 2014 + PHP Tour Luxembourg 2015 : les conférenciers envoient une photo au moment de soumettre leur conf, malheureusement elles ne semblent pas enregistrées puisqu'elles n'apparaissent pas dans la fiche conférencier ensuite.

**Comment by perrick** [comment]
Visiblement c'est corrigé. Je viens de vérifier sur la proposition de conférence que je viens de faire et ça m'a l'air tout bon...
