### ISSUE TITLE
Supprimer l'adresse conferenciers@afup.org et en faire un alias de conferences@.

### ISSUE THREAD

**Issue by communicationafup** [afup/web#87]
L'adresse conférenciers@afup.org est une adresse pop accessible via le webmail comme communication mais on ne sait plus qui est en charge de cette adresse. 
Peut-on fait un alias de conferences@afup.org qui est redirigée vers fabriceb@theodo.fr, maxteneur@gmail.com, rodolfo.ripado@gmail.com, claire.bonachera@gmail.com, perrick@noparking.net, lepinejeanfrancois@yahoo.fr, thierry.marianne.alexandre@gmail.com ?
Merci !

**Comment by jacquesbh** [comment]
C'est bon. conferenciers@afup.org redirige sur conferences@afup.org qui contient les emails actualisés (avec le changement de l'équipe, etc.)
