### ISSUE TITLE
Mlle dans le formulaire de conférencier

### ISSUE THREAD

**Issue by SofLesc** [afup/web#890]
![Capture d’écran 2019-11-22 à 12 12 20](https://user-images.githubusercontent.com/10260380/69428042-9c4b6700-0d30-11ea-8a1e-337130986fc9.png)

**Comment by mikaelrandy** [comment]
Pour préciser : il s'agit d'être dans la lignée de la [directive de 2012 sur le retrait de la distinction Mme/Mlle dans les formulaires](http://circulaire.legifrance.gouv.fr/pdf/2012/02/cir_34682.pdf).

C'est une information qui ne nous apporte rien, et que nous n'avons pas d'intérêt à demander.

Pour aller dans le sens de l'amélioration de l'inclusion, nous pourrions ajouter "Autre", "Neutre" ou "Non genré"

**Comment by SofLesc** [comment]
D'ailleurs cela semble être présent dans tous les formulaires. Je l'ai retrouve dans le formulaire d'incription à l'AFUPDay

**Comment by amenophis** [comment]
@agallou Cette issue peut être fermée je pense

**Comment by SofLesc** [comment]
En effet, je ferme puisque la PR a été mergée
