### ISSUE TITLE
Ajouter le numéro de la facture dans le nom du fichier lorsqu'on la télécharge

### ISSUE THREAD

**Issue by srogier** [afup/web#907]
A partir de l'écran "LISTE FACTURE" au clic sur "Télécharger la facture"

**Comment by nikrou** [comment]
En plus du numéro de facture, ne faudrait-il pas uniformiser ce nom de facture ? Actuellement on a un mix entre quelques fois une référence et d'autres fois une concaténation nom de société, date de facture ?

**Comment by macintoshplus** [comment]
Ce pattern me semble bien : `<nom client>_<numero facture>_<date facture>.pdf`
