### ISSUE TITLE
Inscriptions à un event : supprimer la question sur la PMR

### ISSUE THREAD

**Issue by agallou** [afup/web#918]
Supprimer la question sur le fait que la personne soit à mobilité réduite. Nous faisons en sorte d'avoir des événements accessibles et n'avons donc pas besoin d'avoir l'information qui en soit peux être discriminant.

Au passage l'enlever du BO. on pourrais aussi supprimer l'info en base (ou du moins créer un ticket pour le faire dans un second temps)

**Comment by macintoshplus** [comment]
Réalisé
