### ISSUE TITLE
Changer le texte de la sous-rubrique "élections" sur afup.org

### ISSUE THREAD

**Issue by communicationafup** [afup/web#974]
afup.org => antennes => élections
Il faudrait changer le texte pour indiquer le texte suivant : 

Processus des élections dans les antennes

L'AFUP, constituée en association, a pour valeur fondatrice la démocratie : la voix de chacun compte pour les décisions de l’association, et ses représentants sont choisis par les membres eux-mêmes. C’est pourquoi, tous les ans au mois de février pendant l’Assemblée Générale, le bureau de l’association est renouvelé, et les membres sont invités à donner leur avis sur les directions à prendre pour l’association. Les antennes AFUP, qui prolongent en région les actions de l’association, suivent donc la même règle de fonctionnement. Ses représentants sont choisis par les participants à l’antenne, ils portent un projet dans lequel les participants se retrouvent, et des élections régulières organisées en juin permettent de renouveler les équipes ou de changer de direction, en fonction de la volonté des participants.

 

Calendrier des élections 2020 / COVID19

La date des élections est fixée par l’équipe en place : compte-tenu de la situation sanitaire actuelle, le choix est laissé entre l'organisation d'un vote en juin lors d'une soirée de conférences en ligne, ou d'un vote en septembre lors d'un meetup physique (espérant que la situation le permettra alors).
Vous retrouverez le meet-up relatif à votre ville dans l’onglet “Meetups”.

Le dépôt des listes auprès du pôle antennes devra avoir lieu avant le lundi 1er juin pour des élections en ligne, et le 1er septembre pour des élections en physique.

 

Modalité des élections

- les candidatures
Des élections sont organisées au sein de chaque antenne pour désigner une liste portée par un·e coordinateur·trice et un·e modérateur·trice, et leur éventuelle équipe en soutien. Les votants choisissent une liste et non des personnes individuelles. Les votants choisissent une liste au complet, non des personnes individuelles qui constitueraient au final une équipe. Une liste sortante a le droit de se représenter, dans sa totalité ou avec certains changements. Il n’y a pas de nombre limite de mandats.

Les listes candidates devront être publiées sur l’événement meetup durant lequel l’élection aura lieu.
Pour déposer la candidature de votre liste, contactez le pôle antennes : pole-antennes[at]afup.org .

- durée du mandat
Une liste est élue pour un an, de juin 2020 à juin 2021 ou de septembre 2020 à juin 2021

- corps électoral
Toutes les personnes présentes à la soirée ont le droit de vote, qu’elles soient membres AFUP ou non.

- mode de scrutin
Pour la version en ligne : l'élection se fait grâce à un outil de sondage, les votants votent pour une liste au suffrage direct à un tour. En cas d’égalité parfaite, l’équipe la plus âgée (= la somme de tous les âges) est élue.
Pour la version en physique : ’élection se fait à main levée, les votants votent pour une liste au suffrage direct à un tour. En cas d’égalité parfaite, l’équipe la plus âgée (= la somme de tous les âges) est élue.

- supervision du bureau de l’AFUP
Un membre du bureau de l’AFUP ou un·e de ses représentant·e·s sera présent·e pour les équipes le demandant, afin de les rencontrer et s’assurer de la bonne tenue de l’élection.

 

Des questions ?

Contactez le pôle antennes pour toute question : nous sommes là pour vous aider et vous accompagner. pole-antennes[at]afup.org

**Comment by macintoshplus** [comment]
C'est en ligne.
