### ISSUE TITLE
Erreur 500 lors de la connexion à l'espace conférencier

### ISSUE THREAD

**Issue by macintoshplus** [afup/web#988]
lors de la connexion via GitHub, une erreur 500 se produit lors du retour sur le site:

https://afup.org/connect/github/check?code=2b7...839&state=75omA...oMx7x8

**Comment by agallou** [comment]
```
Jun 22 21:55:28 afupsvr01 [10039]: request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ConnectException: "cURL error 6: Could not resolve host: github.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" at /home/sources/web/releases/20200615090607/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 186 {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 6: Could not resolve host: github.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/sources/web/releases/20200615090607/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186)"} []
```

il y a actuellement des soucis de résolution de nom sur github.com

![Capture d’écran du 2020-06-22 22-00-38](https://user-images.githubusercontent.com/320372/85330155-1fee5180-b4d4-11ea-8899-fd9dcc7e3877.png)

sur https://www.githubstatus.com/

il y a 
```
 Update - An update to our nameservers has been rolled back. We are monitoring recovery.
Jun 22, 20:00 UTC 
```

ça viens donc de Github et il faudra attendre qu'ils aient corrigé le problème pour pouvoir se connecter

**Comment by macintoshplus** [comment]
Merci pour ta réponse rapide.
