### ISSUE TITLE
Le nombre de propositions affichées par speaker est limité à 10

### ISSUE THREAD

**Issue by f2r** [afup/web#989]
Quand un speaker propose plus de 10 sujets sur le CFP, il ne peut pas les voir tous (oui, il y a des speakers qui proposent plus de 10 sujets).

Il faudrait limiter le nombre de sujets que peut proposer un speaker ou augmenter la limite

https://github.com/afup/web/blob/7dbde98aabbb48f0825ce6597d2a9b7b6d32e116/sources/AppBundle/Event/Model/Repository/TalkRepository.php#L57

**Comment by macintoshplus** [comment]
Il viens de passer à 20.
